# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0
import re as module_1


def test_case_0():
    none_type_0 = None
    none_type_1 = module_0.debug(none_type_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    module_1.fullmatch(none_type_0, none_type_0, none_type_0)


def test_case_3():
    none_type_0 = None
    none_type_1 = module_0.debug(none_type_0)
    bool_0 = True
    module_0.get_source(bool_0)


def test_case_4():
    str_0 = ""
    none_type_0 = module_0.warn(str_0)
    none_type_1 = None
    none_type_2 = module_0.debug(none_type_1)


def test_case_5():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    none_type_1 = module_0.warn(callable_0)
    str_0 = "quote_plus"
    none_type_2 = module_0.debug(callable_0)
    none_type_3 = module_0.debug(callable_0)
    none_type_4 = module_0.warn(str_0)
    str_1 = "`$CNt9F1'"
    none_type_5 = module_0.warn(str_1)
    callable_1 = module_0.eager(none_type_3)
    none_type_6 = module_0.debug(str_1)
    callable_1.__call__(str_1, str_1, qualname=none_type_5, start=none_type_5)
