# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.transformers.yield_from as module_0
import typed_ast._ast3 as module_1


def test_case_0():
    none_type_0 = None
    yield_from_transformer_0 = module_0.YieldFromTransformer(none_type_0)
    yield_from_transformer_0.visit(none_type_0)


def test_case_1():
    none_type_0 = None
    yield_from_transformer_0 = module_0.YieldFromTransformer(none_type_0)


def test_case_2():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0]
    yield_from_transformer_0 = module_0.YieldFromTransformer(none_type_0)
    list_1 = [list_0, list_0]
    while_0 = module_1.While(*list_1)
    a_s_t_0 = yield_from_transformer_0.visit(while_0)


def test_case_3():
    none_type_0 = None
    yield_from_transformer_0 = module_0.YieldFromTransformer(none_type_0)
    list_0 = [none_type_0, none_type_0]
    str_0 = "P+>W*v\nDN{M8\x0bLk"
    dict_0 = {
        str_0: yield_from_transformer_0,
        str_0: yield_from_transformer_0,
        str_0: yield_from_transformer_0,
    }
    while_0 = module_1.While(*list_0, **dict_0)
    a_s_t_0 = yield_from_transformer_0.visit(while_0)
