# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    timer_0 = module_0.Timer()


def test_case_1():
    bytes_0 = b"Q\xc3\xc9\xf7["
    timer_error_0 = module_0.TimerError()
    timer_0 = module_0.Timer(initial_text=bytes_0)
    timer_1 = timer_0.__enter__()
    float_arg_0 = module_0.FloatArg()
    timer_0.start()


def test_case_2():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()


def test_case_3():
    timer_0 = module_0.Timer()
    timer_0.__exit__()


def test_case_4():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_1.__exit__()


def test_case_5():
    bytes_0 = b".\xc3\xc9\xf7["
    timer_error_0 = module_0.TimerError()
    timer_0 = module_0.Timer(initial_text=bytes_0)
    none_type_0 = timer_0.start()


def test_case_6():
    timer_error_0 = module_0.TimerError()
    timer_error_1 = module_0.TimerError()
    none_type_0 = None
    timer_error_2 = module_0.TimerError()
    timer_error_3 = module_0.TimerError()
    timer_0 = module_0.Timer(initial_text=timer_error_2, logger=none_type_0)
    none_type_1 = timer_0.start()


def test_case_7():
    bytes_0 = b"Q\xc3\xc9\xf7["
    timer_0 = module_0.Timer(bytes_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()
    timer_error_0 = module_0.TimerError()
    timer_2 = timer_1.__enter__()
    float_1 = timer_1.stop()
    timer_0.__exit__()


def test_case_8():
    str_0 = "4O,W"
    timer_0 = module_0.Timer(initial_text=str_0)
    timer_error_0 = module_0.TimerError()
    timer_1 = module_0.Timer(str_0)
    timer_2 = timer_0.__enter__()
    float_0 = timer_0.stop()
    timer_error_1 = module_0.TimerError()
    timer_3 = timer_0.__enter__()
    float_1 = timer_0.stop()
    var_0 = timer_0.__call__(float_0)
    timer_1.stop()


def test_case_9():
    bytes_0 = b"Q\xc3\xc9"
    timer_0 = module_0.Timer()
    var_0 = timer_0.__eq__(timer_0)
    timer_1 = module_0.Timer(var_0, bytes_0, timer_0)
    timer_2 = timer_0.__enter__()
    float_0 = timer_0.stop()
    timer_error_0 = module_0.TimerError()
    timer_3 = timer_1.__enter__()
    timer_0.stop()


def test_case_10():
    bytes_0 = b"Q\xc3\xc9\xf7["
    timer_0 = module_0.Timer()
    timer_error_0 = module_0.TimerError()
    none_type_0 = None
    timer_1 = module_0.Timer(text=bytes_0, logger=none_type_0)
    timer_2 = timer_1.__enter__()
    float_0 = timer_2.stop()
    timer_error_1 = module_0.TimerError()
    timer_3 = timer_0.__enter__()
    float_1 = timer_3.stop()


def test_case_11():
    bytes_0 = b"Q\xc3\xc9\xf7["
    timer_0 = module_0.Timer()
    timer_error_0 = module_0.TimerError()
    timer_1 = module_0.Timer(bytes_0, timer_0)
    timer_2 = timer_0.__enter__()
    float_0 = timer_2.stop()
    var_0 = timer_1.__eq__(float_0)
    timer_3 = timer_1.__enter__()
    float_1 = timer_3.stop()
    var_1 = var_0.__eq__(timer_0)
    timer_0.stop()
