# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0


def test_case_0():
    bytes_0 = b"\x81Vr#\x07\x07\xa7]"
    none_type_0 = module_0.debug(bytes_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    int_0 = 2955
    callable_0 = module_0.eager(int_0)


def test_case_3():
    none_type_0 = None
    module_0.get_source(none_type_0)


def test_case_4():
    none_type_0 = None
    none_type_1 = module_0.warn(none_type_0)


def test_case_5():
    str_0 = "asname"
    callable_0 = module_0.eager(str_0)
    none_type_0 = module_0.warn(str_0)
    callable_0.__call__(none_type_0, callable_0, qualname=none_type_0, type=str_0)
