# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    float_arg_0 = module_0.FloatArg()


def test_case_1():
    str_0 = '<"KD@p5oh@W\t(@lkI'
    timer_0 = module_0.Timer(initial_text=str_0)
    timer_1 = timer_0.__enter__()
    timer_0.__enter__()


def test_case_2():
    str_0 = '<"KD@p5oh@W\t(@lkI'
    timer_0 = module_0.Timer(initial_text=str_0)
    timer_1 = timer_0.__enter__()


def test_case_3():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    timer_1.stop()


def test_case_4():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()


def test_case_5():
    str_0 = "EYIn"
    none_type_0 = None
    timer_0 = module_0.Timer(str_0, logger=none_type_0)
    none_type_1 = timer_0.start()
    float_0 = timer_0.stop()


def test_case_6():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    timer_2 = module_0.Timer(initial_text=timer_1, logger=timer_1)
    timer_3 = timer_2.__enter__()
    timer_3.__ror__(timer_3)


def test_case_7():
    bool_0 = True
    bool_1 = True
    timer_0 = module_0.Timer(bool_0, bool_0, bool_1)
    none_type_0 = None
    timer_1 = module_0.Timer(none_type_0)
    var_0 = timer_1.__call__(timer_1)
    var_1 = timer_1.__repr__()
    none_type_1 = timer_0.start()
    timer_0.__setitem__(none_type_1, var_1)


def test_case_8():
    timer_0 = module_0.Timer()
    timer_1 = module_0.Timer(text=timer_0, logger=timer_0)
    timer_2 = timer_1.__enter__()
    var_0 = timer_1.__repr__()
    none_type_0 = timer_2.__exit__()
    timer_3 = module_0.Timer()
    timer_4 = timer_1.__enter__()
    var_0.__ror__(var_0)
