# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    config_0 = module_0.Config()
    str_0 = "P"
    config_1 = module_0.Config(config_0, str_0)


def test_case_2():
    config_0 = module_0.Config()
    bool_0 = True
    none_type_0 = config_0.register_type(bool_0)
    none_type_1 = config_0.update()
    var_0 = config_0.update_config(config_0)
    config_0.__getattr__(none_type_1)


def test_case_3():
    config_0 = module_0.Config()
    bool_0 = True
    none_type_0 = config_0.register_type(bool_0)
    none_type_1 = config_0.update()
    config_0.__getattr__(config_0)


def test_case_4():
    none_type_0 = None
    config_0 = module_0.Config()
    config_0.update_config(none_type_0)


def test_case_5():
    str_0 = "R_0\r5:|\r9^mzI!;u|7}\\"
    config_0 = module_0.Config()
    config_0.update_config(str_0)


def test_case_6():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_7():
    none_type_0 = None
    config_0 = module_0.Config()
    none_type_1 = config_0.register_type(none_type_0)
    config_0.__setitem__(none_type_0, none_type_0)


def test_case_8():
    none_type_0 = None
    none_type_1 = None
    config_0 = module_0.Config(env_prefix=none_type_0, converters=none_type_1)


def test_case_9():
    config_0 = module_0.Config()
    var_0 = module_1.isdatadescriptor(config_0)
    var_1 = var_0.__repr__()
    config_1 = module_0.Config(keep_alive=var_1)
    var_0.update_config(var_0)


def test_case_10():
    none_type_0 = None
    bytes_0 = b"Length Required"
    module_0.Config(none_type_0, none_type_0, converters=bytes_0)


def test_case_11():
    none_type_0 = None
    config_0 = module_0.Config()
    none_type_1 = config_0.register_type(none_type_0)
    config_1 = module_0.Config(keep_alive=none_type_0, converters=config_0)
    var_0 = module_1.isdatadescriptor(config_1)
    var_1 = config_1.update_config(config_0)
    var_2 = module_1.isdatadescriptor(config_1)
    config_1.update_config(var_2)


def test_case_12():
    none_type_0 = None
    config_0 = module_0.Config()
    bool_0 = True
    none_type_1 = config_0.register_type(none_type_0)
    config_1 = module_0.Config(keep_alive=bool_0)
    str_0 = "LOCAL_CERT_CREATOR"
    config_1.__setitem__(str_0, none_type_1)


def test_case_13():
    config_0 = module_0.Config()
    bool_0 = True
    none_type_0 = config_0.register_type(bool_0)
    none_type_1 = config_0.update(**config_0)
    str_0 = "u"
    none_type_2 = config_0.__setattr__(str_0, none_type_1)
    str_1 = "P"
    config_1 = module_0.Config(config_0, str_1)
    config_0.load_environment_vars(str_1)
