# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.yield_from as module_1


def test_case_0():
    call_0 = module_0.Call()
    yield_from_transformer_0 = module_1.YieldFromTransformer(call_0)
    a_s_t_0 = yield_from_transformer_0.visit(call_0)


def test_case_1():
    none_type_0 = None
    yield_from_transformer_0 = module_1.YieldFromTransformer(none_type_0)


def test_case_2():
    dict_0 = {}
    float_0 = -3304.989026
    yield_from_transformer_0 = module_1.YieldFromTransformer(float_0)
    list_0 = [yield_from_transformer_0, dict_0, float_0]
    try_0 = module_0.Try(*list_0)
    var_0 = yield_from_transformer_0.visit(try_0)


def test_case_3():
    expr_0 = module_0.Expr()
    yield_from_transformer_0 = module_1.YieldFromTransformer(expr_0)
    list_0 = [expr_0, yield_from_transformer_0]
    list_1 = [list_0]
    try_0 = module_0.Try(*list_1)
    yield_from_transformer_0.visit(try_0)
