# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0


def test_case_0():
    dict_0 = {}
    module_0.has_message_body(dict_0)


def test_case_1():
    str_0 = "__TERMINATE__"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    bool_0 = True
    module_0.is_hop_by_hop_header(bool_0)


def test_case_4():
    default_0 = module_0.Default()
    var_0 = default_0.__repr__()


def test_case_5():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    bool_0 = module_0.is_atty()
    int_0 = -1539
    module_0.is_hop_by_hop_header(int_0)


def test_case_6():
    bool_0 = module_0.is_atty()
    int_0 = 511
    var_0 = module_0.has_message_body(int_0)
    bool_1 = module_0.is_atty()
    var_1 = var_0.__repr__()
    var_2 = var_1.__repr__()


def test_case_7():
    str_0 = "__TERMINATE__"
    bool_0 = True
    dict_0 = {str_0: str_0, str_0: str_0, str_0: bool_0}
    var_0 = module_0.remove_entity_headers(dict_0)
    var_1 = module_0.has_message_body(bool_0)


def test_case_8():
    int_0 = 304
    var_0 = module_0.has_message_body(int_0)
    var_1 = var_0.__repr__()
    var_2 = module_0.has_message_body(var_0)
    module_0.remove_entity_headers(var_2, var_2)
