# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0
import builtins as module_1


def test_case_0():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    immutable_list_1 = immutable_list_0.unshift(bool_0)
    immutable_list_1.find(immutable_list_1)


def test_case_1():
    bool_0 = False
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    str_0 = immutable_list_0.__str__()
    bool_1 = immutable_list_0.__eq__(bool_0)
    str_1 = immutable_list_0.__str__()
    str_2 = "q!|Oz`sPy"
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_0.__add__(str_2)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.unshift(immutable_list_0)


def test_case_3():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__len__()


def test_case_4():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(bool_0)
    str_0 = immutable_list_0.__len__()
    immutable_list_0.find(immutable_list_0)


def test_case_5():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(bool_0)
    str_0 = immutable_list_0.__str__()
    immutable_list_0.find(immutable_list_0)


def test_case_6():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    str_0 = "q!|Oz`sPy"
    int_0 = 776
    immutable_list_1 = immutable_list_0.unshift(int_0)
    var_0 = immutable_list_1.to_list()
    immutable_list_1.find(str_0)


def test_case_7():
    str_0 = "J+\rCGc]T"
    list_0 = []
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(list_0, is_empty=bool_0)
    immutable_list_1 = immutable_list_0.append(str_0)
    str_1 = immutable_list_1.__str__()
    immutable_list_0.map(immutable_list_0)


def test_case_8():
    bool_0 = False
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    str_0 = immutable_list_0.to_list()
    bool_1 = immutable_list_0.__eq__(bool_0)
    str_1 = immutable_list_0.__str__()
    str_2 = "q!|Oz`sPy"
    str_3 = 'Em~Bb"G'
    int_0 = 776
    immutable_list_1 = immutable_list_0.append(int_0)
    immutable_list_2 = immutable_list_1.__add__(immutable_list_0)
    immutable_list_3 = immutable_list_2.unshift(str_2)
    var_0 = immutable_list_2.__len__()
    var_1 = immutable_list_0.find(var_0)
    var_2 = immutable_list_2.reduce(var_1, immutable_list_0)
    immutable_list_4 = module_0.ImmutableList(str_3)
    immutable_list_1.map(bool_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_10():
    list_0 = []
    object_0 = module_1.object(*list_0)
    immutable_list_0 = module_0.ImmutableList(tail=object_0)
    var_0 = immutable_list_0.reduce(object_0, object_0)
    immutable_list_0.filter(var_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__len__()
    var_1 = immutable_list_0.find(var_0)


def test_case_12():
    int_0 = 723
    immutable_list_0 = module_0.ImmutableList(int_0, int_0)
    immutable_list_0.find(immutable_list_0)


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)


def test_case_14():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_1 = immutable_list_1.__len__()
    immutable_list_0.reduce(var_1, immutable_list_1)


def test_case_15():
    immutable_list_0 = module_0.ImmutableList()


def test_case_16():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.append(immutable_list_0)


def test_case_17():
    bool_0 = True
    str_0 = "q!|Oz`sPy"
    immutable_list_0 = module_0.ImmutableList(str_0, is_empty=str_0)
    immutable_list_1 = immutable_list_0.append(bool_0)
    immutable_list_2 = immutable_list_1.__add__(immutable_list_0)
    immutable_list_0.find(immutable_list_0)


def test_case_18():
    bool_0 = True
    str_0 = "q!|Oz`sPy"
    str_1 = 'Em~Bb"G'
    immutable_list_0 = module_0.ImmutableList(str_1, is_empty=str_0)
    immutable_list_1 = immutable_list_0.append(bool_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_0.find(var_0)


def test_case_19():
    bytes_0 = b"\x82R"
    immutable_list_0 = module_0.ImmutableList(tail=bytes_0)
    str_0 = ""
    immutable_list_1 = module_0.ImmutableList()
    immutable_list_2 = immutable_list_1.unshift(str_0)
    immutable_list_3 = immutable_list_1.append(str_0)
    var_0 = immutable_list_2.__len__()
    float_0 = -568.8
    immutable_list_2.reduce(float_0, bytes_0)


def test_case_20():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(bool_0, is_empty=bool_0)
    immutable_list_0.find(bool_0)


def test_case_21():
    bool_0 = True
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    str_0 = immutable_list_0.to_list()
    bool_1 = immutable_list_0.__eq__(bool_0)
    str_1 = immutable_list_0.__str__()
    str_2 = "q!|Oz`sPy"
    immutable_list_1 = immutable_list_0.unshift(str_2)
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_2 = immutable_list_0.unshift(none_type_0)
    bool_2 = immutable_list_0.__eq__(immutable_list_1)
    immutable_list_2.filter(immutable_list_1)


def test_case_22():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__len__()
    immutable_list_1 = immutable_list_0.unshift(bool_0)
    immutable_list_2 = immutable_list_0.append(immutable_list_1)
    bool_1 = immutable_list_0.__eq__(immutable_list_2)
    immutable_list_1.find(immutable_list_1)
