name: analysis_env
dependencies:
  - python=3.12
  - conda-forge::numpy
  - conda-forge::scipy=1.12
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::pymc
  - conda-forge::ipywidgets
  - pip
  - pip:
    - formulaic==1.0.1