# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import inspect as module_1


def test_case_0():
    dict_0 = {}
    module_0.has_message_body(dict_0)


def test_case_1():
    bytes_0 = b"Reset Content"
    module_0.remove_entity_headers(bytes_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    int_0 = 1424
    module_0.is_entity_header(int_0)


def test_case_4():
    str_0 = "[|ty^\r@9"
    var_0 = module_0.is_hop_by_hop_header(str_0)
    var_1 = module_1.ismodule(var_0)
    var_2 = var_1.__repr__()


def test_case_5():
    float_0 = -3199.40946
    module_0.remove_entity_headers(float_0, float_0)


def test_case_6():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    dict_0 = {}
    module_0.has_message_body(dict_0)


def test_case_7():
    int_0 = 203
    var_0 = module_0.has_message_body(int_0)


def test_case_8():
    bool_0 = module_0.is_atty()
    bool_1 = module_0.has_message_body(bool_0)


def test_case_9():
    dict_0 = {}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_10():
    str_0 = "yK\t"
    dict_0 = {str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_11():
    str_0 = "yK\t"
    bool_0 = module_0.is_atty()
    var_0 = module_0.is_hop_by_hop_header(str_0)
    var_1 = var_0.__repr__()
    dict_0 = {var_1: str_0}
    var_2 = module_0.remove_entity_headers(dict_0)
    str_1 = var_0.__str__()
    default_0 = module_0.Default()
    str_2 = var_2.__str__()
    str_3 = default_0.__str__()
    float_0 = 144.6636
    var_3 = default_0.__repr__()
    int_0 = 204
    var_4 = module_0.has_message_body(int_0)
    var_5 = var_2.__repr__()
    var_6 = var_2.__repr__()
    var_7 = module_0.has_message_body(float_0)
    var_8 = default_0.__repr__()
    var_9 = module_0.has_message_body(var_0)
    module_0.is_entity_header(float_0)
