# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0


def test_case_0():
    complex_0 = -753.78 - 2221.72j
    module_0.has_message_body(complex_0)


def test_case_1():
    bool_0 = module_0.is_atty()
    module_0.remove_entity_headers(bool_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    default_0 = module_0.Default()


def test_case_4():
    bytes_0 = b"\xe9$\x1c\x00\x19d\xd4\xe5"
    var_0 = module_0.is_entity_header(bytes_0)


def test_case_5():
    list_0 = []
    module_0.is_hop_by_hop_header(list_0)


def test_case_6():
    default_0 = module_0.Default()
    var_0 = default_0.__repr__()


def test_case_7():
    bool_0 = module_0.is_atty()
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    int_0 = 203
    var_0 = module_0.has_message_body(int_0)
    bool_1 = module_0.is_atty()


def test_case_8():
    bool_0 = module_0.is_atty()
    var_0 = module_0.has_message_body(bool_0)
    var_1 = var_0.__repr__()


def test_case_9():
    int_0 = 774
    var_0 = module_0.has_message_body(int_0)
    bool_0 = True
    module_0.import_string(bool_0)


def test_case_10():
    int_0 = -3390
    dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0}
    module_0.remove_entity_headers(dict_0)


def test_case_11():
    str_0 = "G"
    dict_0 = {
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
    }
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_12():
    str_0 = ""
    dict_0 = {
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
    }
    bool_0 = module_0.is_atty()
    var_0 = module_0.has_message_body(bool_0)
    var_1 = module_0.remove_entity_headers(dict_0)
    default_0 = module_0.Default()
    var_2 = var_1.__repr__()
    str_1 = default_0.__str__()
    int_0 = 204
    var_3 = module_0.has_message_body(int_0)
    var_4 = module_0.is_hop_by_hop_header(var_2)
    var_5 = default_0.__repr__()
    var_6 = module_0.is_hop_by_hop_header(str_1)
    str_2 = var_2.__str__()
    bool_1 = module_0.is_atty()


def test_case_13():
    str_0 = "last-modified"
    dict_0 = {
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
    }
    var_0 = module_0.remove_entity_headers(dict_0)
    default_0 = module_0.Default()
    module_0.is_hop_by_hop_header(dict_0)


def test_case_14():
    str_0 = "content-type"
    dict_0 = {
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
        str_0: str_0,
    }
    var_0 = module_0.remove_entity_headers(dict_0, dict_0)
    default_0 = module_0.Default()
    str_1 = var_0.__str__()
    module_0.has_message_body(str_1)
