# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast.ast3 as module_0
import typed_ast._ast3 as module_1
import py_backwards.transformers.dict_unpacking as module_2


def test_case_0():
    bool_0 = True
    module_0.get_docstring(bool_0)


def test_case_1():
    is_0 = module_1.Is()
    dict_unpacking_transformer_0 = module_2.DictUnpackingTransformer(is_0)
    dict_unpacking_transformer_0.visit_Module(dict_unpacking_transformer_0)
