# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import httpie.plugins.base as module_0


def test_case_0():
    transport_plugin_0 = module_0.TransportPlugin()


def test_case_1():
    auth_plugin_0 = module_0.AuthPlugin()
    base_plugin_0 = module_0.BasePlugin()
    auth_plugin_0.get_auth()


def test_case_2():
    transport_plugin_0 = module_0.TransportPlugin()
    transport_plugin_1 = module_0.TransportPlugin()
    transport_plugin_1.get_adapter()


def test_case_3():
    transport_plugin_0 = module_0.TransportPlugin()
    transport_plugin_1 = module_0.TransportPlugin()
    var_0 = module_0.ConverterPlugin(transport_plugin_0)


def test_case_4():
    bytes_0 = b"\xf0\x94\t\xd8\xb5\xdc\xfa!1%\xdc\xeaq\xaa\x0b"
    bool_0 = False
    converter_plugin_0 = module_0.ConverterPlugin(bool_0)
    converter_plugin_0.convert(bytes_0)


def test_case_5():
    module_0.FormatterPlugin()
