# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.validation as module_0


def test_case_0():
    bytes_0 = b"\x85\xd6l="
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.__eq__(bytes_0)
    var_1 = var_0.__str__()
    var_2 = validation_0.to_maybe()
    var_3 = validation_0.is_success()


def test_case_1():
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__str__()
    bool_0 = False
    validation_1 = module_0.Validation(var_0, bool_0)


def test_case_2():
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(validation_0)
    bytes_1 = b""
    validation_1 = module_0.Validation(bytes_1, bytes_1)
    var_1 = validation_1.to_either()
    validation_0.bind(set_0)


def test_case_3():
    str_0 = "a-j"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_either()
    var_1 = var_0.to_maybe()
    var_1.is_success()


def test_case_4():
    complex_0 = 1560.674 - 3106.251617j
    validation_0 = module_0.Validation(complex_0, complex_0)


def test_case_5():
    bool_0 = True
    validation_0 = module_0.Validation(bool_0, bool_0)
    validation_0.to_either()


def test_case_6():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    validation_0.is_fail()


def test_case_7():
    none_type_0 = None
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    bytes_1 = b"\x85\xb5l="
    validation_1 = module_0.Validation(bytes_1, bytes_1)
    var_1 = validation_0.__str__()
    validation_2 = module_0.Validation(validation_0, none_type_0)
    validation_0.map(var_1)


def test_case_8():
    none_type_0 = None
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    validation_0.bind(set_0)


def test_case_9():
    none_type_0 = None
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    bytes_1 = b"\x85\xb5l="
    validation_1 = module_0.Validation(bytes_1, bytes_1)
    int_0 = 291
    int_1 = 1158
    var_1 = validation_1.__eq__(int_1)
    validation_1.ap(int_0)


def test_case_10():
    str_0 = "h$8#z2n'm-HPV`kC4NKK"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_box()


def test_case_11():
    none_type_0 = None
    set_0 = {none_type_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    bytes_0 = b"\xd6l"
    var_1 = validation_0.to_lazy()
    validation_1 = module_0.Validation(bytes_0, bytes_0)
    int_0 = 291
    var_2 = validation_1.__eq__(int_0)
    validation_2 = module_0.Validation(bytes_0, none_type_0)
    var_3 = validation_0.to_box()
    var_4 = validation_0.to_maybe()


def test_case_12():
    bytes_0 = b"\xe4\xbd6\x13m1\xf0\x93"
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.to_lazy()
    var_1 = var_0.to_maybe()
    var_2 = var_1.to_lazy()
    var_3 = var_2.to_maybe()
    var_4 = var_3.to_either()
    var_4.ap(bytes_0)


def test_case_13():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    validation_0.to_try()


def test_case_14():
    bytes_0 = b"\xa1g"
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.__eq__(validation_0)
    bytes_1 = b"\x85\xb5l="
    validation_1 = module_0.Validation(bytes_1, bytes_1)
    validation_0.bind(var_0)


def test_case_15():
    bytes_0 = b"\xa1g"
    set_0 = {bytes_0}
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(validation_0)
    bytes_1 = b"\x85\xb5l="
    validation_1 = module_0.Validation(var_0, bytes_1)
    var_1 = validation_1.__eq__(validation_0)
    validation_1.bind(bytes_1)


def test_case_16():
    none_type_0 = None
    set_0 = set()
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    var_1 = var_0.__str__()
    str_0 = "#3DKq\tqyCRB7uR"
    validation_1 = module_0.Validation(str_0, str_0)
    var_2 = validation_0.to_try()
    var_3 = validation_0.__str__()
    var_0.to_lazy()


def test_case_17():
    none_type_0 = None
    set_0 = set()
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.__eq__(none_type_0)
    validation_1 = module_0.Validation(none_type_0, validation_0)
    int_0 = 289
    var_1 = validation_0.to_maybe()
    bytes_0 = b"\xe3\xd3\x19\xdeW\xb9\x02*\xb5\xca\xe1\xc4"
    var_2 = validation_1.__eq__(bytes_0)
    var_3 = var_1.to_either()
    var_4 = var_1.__eq__(var_3)
    validation_2 = module_0.Validation(bytes_0, validation_1)
    var_3.bind(int_0)
