# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.yield_from as module_1


def test_case_0():
    div_0 = module_0.Div()
    yield_from_transformer_0 = module_1.YieldFromTransformer(div_0)
    yield_from_transformer_0.visit(yield_from_transformer_0)


def test_case_1():
    div_0 = module_0.Div()
    yield_from_transformer_0 = module_1.YieldFromTransformer(div_0)


def test_case_2():
    div_0 = module_0.Div()
    yield_from_transformer_0 = module_1.YieldFromTransformer(div_0)
    list_0 = [div_0, yield_from_transformer_0]
    with_0 = module_0.With(*list_0)
    a_s_t_0 = yield_from_transformer_0.visit(with_0)


def test_case_3():
    div_0 = module_0.Div()
    yield_from_transformer_0 = module_1.YieldFromTransformer(div_0)
    list_0 = [yield_from_transformer_0, div_0, yield_from_transformer_0, div_0]
    list_1 = [yield_from_transformer_0, list_0]
    with_0 = module_0.With(*list_1)
    a_s_t_0 = yield_from_transformer_0.visit(with_0)
