# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    timer_error_0 = module_0.TimerError()


def test_case_1():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()


def test_case_2():
    str_0 = "name"
    timer_0 = module_0.Timer(initial_text=str_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()
    timer_1.stop()


def test_case_3():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    float_0 = timer_1.stop()


def test_case_4():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_1.__exit__()


def test_case_5():
    int_0 = 5546
    timer_0 = module_0.Timer(initial_text=int_0)
    timer_1 = timer_0.__enter__()


def test_case_6():
    int_0 = 5546
    timer_0 = module_0.Timer(initial_text=int_0)
    float_arg_0 = module_0.FloatArg()
    timer_1 = timer_0.__enter__()
    timer_0.start()


def test_case_7():
    str_0 = "name"
    none_type_0 = None
    timer_0 = module_0.Timer(str_0, logger=none_type_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()


def test_case_8():
    str_0 = "name"
    timer_0 = module_0.Timer(initial_text=str_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()


def test_case_9():
    str_0 = "name"
    timer_0 = module_0.Timer(str_0, str_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_1.stop()
    timer_1.stop()


def test_case_10():
    int_0 = -767
    timer_0 = module_0.Timer(logger=int_0)
    int_1 = 5546
    timer_1 = module_0.Timer(int_1, initial_text=timer_0, logger=int_1)
    timer_1.__enter__()


def test_case_11():
    int_0 = -720
    timer_0 = module_0.Timer(logger=int_0)
    timer_1 = module_0.Timer(text=timer_0, initial_text=int_0)
    timer_2 = timer_1.__enter__()
    none_type_0 = timer_1.__exit__()
    timer_3 = timer_2.__enter__()
    var_0 = timer_1.__call__(timer_0)
    var_0.__iter__()
