# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import re as module_0
import py_backwards.utils.helpers as module_1


def test_case_0():
    var_0 = module_0.purge()
    none_type_0 = module_1.debug(var_0)


def test_case_1():
    variables_generator_0 = module_1.VariablesGenerator()


def test_case_2():
    none_type_0 = None
    callable_0 = module_1.eager(none_type_0)
    list_0 = [none_type_0]
    str_0 = "@f'"
    none_type_1 = module_1.warn(str_0)
    none_type_2 = module_1.debug(str_0)
    dict_0 = {str_0: list_0, str_0: list_0, str_0: str_0}
    module_1.VariablesGenerator(**dict_0)


def test_case_3():
    none_type_0 = None
    module_1.get_source(none_type_0)


def test_case_4():
    str_0 = 'V-jy\\Yz%"\nIk;0N9bFEr'
    none_type_0 = module_1.warn(str_0)
    variables_generator_0 = module_1.VariablesGenerator()


def test_case_5():
    none_type_0 = None
    callable_0 = module_1.eager(none_type_0)
    list_0 = [none_type_0]
    str_0 = "\n"
    var_0 = module_1.eager(callable_0)
    str_1 = "@f'"
    none_type_1 = module_1.warn(str_1)
    none_type_2 = module_1.debug(str_1)
    var_0.__call__(str_0, list_0, module=list_0)
