# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    timer_0 = module_0.Timer()


def test_case_1():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()


def test_case_2():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0]
    timer_0 = module_0.Timer()
    timer_0.__exit__(*list_0)


def test_case_3():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    float_0 = timer_0.stop()


def test_case_4():
    none_type_0 = None
    bool_0 = True
    timer_0 = module_0.Timer(none_type_0, initial_text=bool_0, logger=none_type_0)
    timer_1 = timer_0.__enter__()
    var_0 = timer_1.__repr__()
    none_type_1 = timer_0.__exit__(*var_0)
    var_0.setdefault(bool_0)


def test_case_5():
    none_type_0 = None
    bool_0 = True
    timer_0 = module_0.Timer(none_type_0, initial_text=bool_0)
    timer_1 = timer_0.__enter__()


def test_case_6():
    none_type_0 = None
    timer_0 = module_0.Timer(none_type_0)
    timer_1 = timer_0.__enter__()
    timer_1.__enter__()


def test_case_7():
    none_type_0 = None
    bool_0 = True
    timer_0 = module_0.Timer(bool_0, none_type_0, bool_0)
    timer_1 = timer_0.__enter__()


def test_case_8():
    bool_0 = True
    timer_0 = module_0.Timer(bool_0, initial_text=bool_0)
    timer_1 = timer_0.__enter__()
    float_0 = timer_1.stop()
    list_0 = [timer_0]
    timer_1.__exit__(*list_0)


def test_case_9():
    str_0 = "SWbF;"
    timer_0 = module_0.Timer(logger=str_0)
    timer_1 = module_0.Timer(initial_text=str_0)
    var_0 = timer_1.__repr__()
    timer_2 = timer_1.__enter__()
    var_0.__setitem__(timer_1, var_0)


def test_case_10():
    none_type_0 = None
    bool_0 = True
    timer_0 = module_0.Timer(none_type_0, initial_text=bool_0)
    timer_1 = timer_0.__enter__()
    timer_2 = module_0.Timer(text=timer_0)
    timer_3 = timer_2.__enter__()
    float_0 = timer_3.stop()
    timer_3.__exit__()
