# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0


def test_case_0():
    str_0 = "4+(O[e"
    none_type_0 = module_0.debug(str_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    variables_generator_0 = module_0.VariablesGenerator()
    callable_0 = module_0.eager(variables_generator_0)


def test_case_3():
    str_0 = ",\".\n'N'|mC~Gp[o-"
    none_type_0 = module_0.warn(str_0)
    module_0.get_source(none_type_0)


def test_case_4():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    complex_0 = -1789 + 2546.74j
    str_0 = "-t"
    callable_0.__call__(none_type_0, str_0, module=complex_0, type=none_type_0)
