# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import inspect as module_1


def test_case_0():
    int_0 = -1354
    var_0 = module_0.has_message_body(int_0)


def test_case_1():
    none_type_0 = None
    module_0.remove_entity_headers(none_type_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    str_0 = "]\x0b5^']P580Sal~[L="
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0, dict_0)


def test_case_4():
    bool_0 = module_0.is_atty()
    default_0 = module_0.Default()
    module_0.is_hop_by_hop_header(bool_0)


def test_case_5():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    dict_0 = {str_0: default_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_6():
    float_0 = 1939.3
    bool_0 = module_0.is_atty()
    var_0 = module_0.has_message_body(float_0)
    var_1 = module_0.has_message_body(float_0)
    module_0.remove_entity_headers(float_0)


def test_case_7():
    int_0 = 304
    var_0 = module_0.has_message_body(int_0)
    var_1 = var_0.__repr__()
    str_0 = var_1.__str__()
    float_0 = 30.4
    bool_0 = module_0.is_atty()
    str_1 = var_0.__str__()
    var_2 = module_0.has_message_body(var_0)
    str_2 = var_0.__str__()
    dict_0 = {str_1: float_0}
    var_3 = module_0.remove_entity_headers(dict_0)
    var_4 = module_0.has_message_body(var_2)
    var_5 = module_0.has_message_body(var_4)
    var_6 = var_2.__repr__()
    str_3 = var_2.__str__()
    var_7 = module_1.ismodule(var_0)
    module_0.is_hop_by_hop_header(var_7)
