# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    float_0 = 2302.0
    str_0 = "shared_5ctx"
    config_0 = module_0.Config(env_prefix=str_0, keep_alive=str_0)
    none_type_0 = None
    var_0 = module_1.isdatadescriptor(none_type_0)
    module_0.DescriptorMeta(float_0)


def test_case_2():
    config_0 = module_0.Config()
    none_type_0 = None
    none_type_1 = config_0.register_type(none_type_0)
    none_type_2 = None
    config_1 = module_0.Config()
    var_0 = config_0.update_config(config_0)
    var_1 = module_1.getmembers(none_type_1)
    config_2 = module_0.Config(config_0)
    config_1.update_config(none_type_2)


def test_case_3():
    config_0 = module_0.Config()
    str_0 = "--coff4ee"
    descriptor_meta_0 = module_1.isclass(str_0)
    config_0.__getattr__(descriptor_meta_0)


def test_case_4():
    config_0 = module_0.Config()
    list_0 = [config_0]
    none_type_0 = config_0.update(*list_0)
    config_1 = module_0.Config()
    config_0.__getattr__(config_0)


def test_case_5():
    config_0 = module_0.Config()
    none_type_0 = None
    config_0.update_config(none_type_0)


def test_case_6():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_7():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)
    none_type_0 = config_0.update()
    config_1 = module_0.Config(env_prefix=none_type_0)
    config_1.update_config(none_type_0)


def test_case_8():
    str_0 = ""
    config_0 = module_0.Config()
    config_0.load_environment_vars(str_0)


def test_case_9():
    config_0 = module_0.Config()
    none_type_0 = config_0.register_type(config_0)
    none_type_1 = config_0.update()
    var_0 = config_0.update_config(config_0)
    config_1 = module_1.isdatadescriptor(config_0)
    var_0.respond(none_type_1)


def test_case_10():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)
    config_0.__setitem__(config_0, config_0)


def test_case_11():
    int_0 = 200
    module_0.Config(env_prefix=int_0, converters=int_0)


def test_case_12():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0, none_type_0)
    none_type_1 = config_0.register_type(none_type_0)
    var_0 = config_0.load_environment_vars()
    str_0 = "lx6G#Ep"
    bool_0 = False
    config_1 = module_0.Config()
    dict_0 = {str_0: bool_0, bool_0: bool_0}
    bool_1 = False
    config_2 = module_0.Config(keep_alive=bool_1, converters=str_0)
    config_2.update_config(dict_0)


def test_case_13():
    config_0 = module_0.Config()
    none_type_0 = config_0.update()
    none_type_1 = config_0.register_type(config_0)
    var_0 = config_0.update_config(config_0)
    var_1 = config_0.update_config(config_0)
    str_0 = "G\ndJ5W:ze^"
    config_0.update_config(str_0)


def test_case_14():
    config_0 = module_0.Config()
    none_type_0 = config_0.register_type(config_0)
    config_0.register_type(config_0)
