# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import flutils.setuputils.cfg as module_0
import flutils.setuputils.cmd as module_1


def test_case_0():
    module_0.SetupCfgCommandConfig()


def test_case_1():
    bytes_0 = b"\xaf\xbf\x8fV\x02\xab\x1f\x04w"
    module_1.build_setup_cfg_command_class(bytes_0)
