# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)


def test_case_1():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(dict_0)
    immutable_list_2.find(immutable_list_1)


def test_case_2():
    int_0 = -832
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.append(int_0)


def test_case_3():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    bool_0 = False
    immutable_list_1 = module_0.ImmutableList(is_empty=bool_0)
    var_1 = var_0.__len__()
    immutable_list_1.__add__(var_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__len__()
    immutable_list_1 = var_0.__add__(var_0)
    immutable_list_2 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_0.map(var_0)


def test_case_5():
    none_type_0 = None
    tuple_0 = (none_type_0,)
    immutable_list_0 = module_0.ImmutableList(tuple_0, is_empty=tuple_0)
    var_0 = immutable_list_0.__len__()
    var_0.__len__()


def test_case_6():
    int_0 = -832
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    var_1 = immutable_list_0.reduce(var_0, immutable_list_0)
    immutable_list_1 = immutable_list_0.append(int_0)


def test_case_7():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(dict_0)
    bool_0 = immutable_list_2.to_list()
    immutable_list_2.find(immutable_list_1)


def test_case_8():
    str_0 = "cn'`%6"
    float_0 = 1483.67424
    immutable_list_0 = module_0.ImmutableList(tail=float_0, is_empty=float_0)
    immutable_list_1 = immutable_list_0.unshift(float_0)
    var_0 = immutable_list_0.find(str_0)
    immutable_list_0.map(var_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_10():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(is_empty=bool_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_0 = immutable_list_1.find(bool_0)
    str_0 = immutable_list_0.__str__()
    var_1 = immutable_list_0.find(immutable_list_0)
    immutable_list_2 = immutable_list_0.unshift(var_1)
    var_2 = immutable_list_1.reduce(immutable_list_2, immutable_list_2)
    immutable_list_2.filter(var_1)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    var_1 = immutable_list_0.find(var_0)
    immutable_list_0.filter(var_1)


def test_case_12():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_13():
    bool_0 = False
    bool_1 = True
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(bool_0)
    immutable_list_2 = immutable_list_1.append(bool_0)
    immutable_list_3 = immutable_list_2.unshift(bool_1)
    immutable_list_4 = immutable_list_3.unshift(bool_1)
    immutable_list_5 = module_0.ImmutableList(tail=bool_1)
    immutable_list_4.reduce(immutable_list_4, immutable_list_1)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()


def test_case_15():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    str_0 = immutable_list_1.__str__()
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(dict_0)
    immutable_list_2.find(immutable_list_1)


def test_case_16():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.unshift(dict_0)
    immutable_list_1.find(immutable_list_1)


def test_case_17():
    bytes_0 = b"\x0c"
    immutable_list_0 = module_0.ImmutableList(tail=bytes_0)
    immutable_list_0.append(bytes_0)


def test_case_18():
    tuple_0 = ()
    immutable_list_0 = module_0.ImmutableList(tuple_0)
    immutable_list_0.find(tuple_0)


def test_case_19():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(dict_0)
    var_0 = immutable_list_2.__len__()
    immutable_list_2.find(immutable_list_1)


def test_case_20():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(is_empty=dict_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = immutable_list_1.unshift(dict_0)
    bool_0 = immutable_list_1.__eq__(immutable_list_2)
    immutable_list_2.find(immutable_list_1)


def test_case_21():
    bytes_0 = b"'\xddX\x86K\xed\xef\xeaO\xea*\xcf"
    bytes_1 = b"\xd5\x10\x1d\xef\x9b7\xc9\xb3\xb0\xf1\xf2\xed\x98\xe8\x17*\xca"
    immutable_list_0 = module_0.ImmutableList(bytes_1, is_empty=bytes_1)
    immutable_list_0.reduce(bytes_0, bytes_0)
