# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import sanic.http.http1 as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    none_type_0 = None
    config_0 = module_0.Config(converters=none_type_0)
    none_type_1 = None
    bytes_0 = b"\x8eGI[c\xacb\x86\xf8\xc7\xab\x90\xbf\xfa\x05\xfa)"
    none_type_2 = config_0.register_type(bytes_0)
    str_0 = "$~"
    none_type_3 = config_0.__setattr__(str_0, none_type_0)
    config_1 = module_0.Config(env_prefix=none_type_1, keep_alive=none_type_1)
    config_2 = module_0.Config(keep_alive=none_type_2, converters=config_0)


def test_case_2():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_3():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0)
    config_0.update_config(none_type_0)


def test_case_4():
    bool_0 = True
    config_0 = module_0.Config(keep_alive=bool_0)
    module_1.Http(bool_0)


def test_case_5():
    config_0 = module_0.Config()
    config_1 = module_0.Config()
    var_0 = config_0.update_config(config_1)
    var_1 = config_1.update_config(config_1)
    none_type_0 = None
    config_2 = module_0.Config(env_prefix=var_0, keep_alive=none_type_0)
    var_0.update_config(none_type_0)


def test_case_6():
    float_0 = -906.0
    dict_0 = {float_0: float_0}
    config_0 = module_0.Config(dict_0)


def test_case_7():
    config_0 = module_0.Config()
    config_0.__getattr__(config_0)


def test_case_8():
    str_0 = "INSPECTOR"
    config_0 = module_0.Config(env_prefix=str_0)
    bytes_0 = b"\xa9\xce\xd2\xfe\x18\x92\x99j\xb6"
    config_0.update_config(bytes_0)


def test_case_9():
    none_type_0 = None
    config_0 = module_0.Config(converters=none_type_0)
    bool_0 = True
    none_type_1 = None
    bytes_0 = b"\x8eGI[c\xacb\x86\xf8\xc7\xab\x90\xbf\xfa\x05\xfa)"
    none_type_2 = config_0.register_type(bytes_0)
    str_0 = "$~"
    none_type_3 = config_0.__setattr__(str_0, none_type_0)
    config_1 = module_0.Config(env_prefix=none_type_1, keep_alive=none_type_1)
    config_1.update_config(bool_0)


def test_case_10():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)
    config_0.__setitem__(var_0, config_0)


def test_case_11():
    config_0 = module_0.Config()
    module_1.Http(config_0)


def test_case_12():
    str_0 = "0B[xPvu3|_UJmJJQ)k8"
    module_0.Config(converters=str_0)


def test_case_13():
    none_type_0 = None
    config_0 = module_0.Config(converters=none_type_0)
    str_0 = "LOCAL_CERT_CREATOR"
    config_0.__setattr__(str_0, config_0)


def test_case_14():
    none_type_0 = None
    str_0 = ""
    config_0 = module_0.Config(env_prefix=none_type_0, keep_alive=none_type_0)
    config_0.load_environment_vars(str_0)
