# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.yield_from as module_1


def test_case_0():
    mod_0 = module_0.mod()
    yield_from_transformer_0 = module_1.YieldFromTransformer(mod_0)
    a_s_t_0 = yield_from_transformer_0.visit(mod_0)


def test_case_1():
    mod_0 = module_0.mod()
    yield_from_transformer_0 = module_1.YieldFromTransformer(mod_0)


def test_case_2():
    str_0 = "(dxX"
    yield_from_transformer_0 = module_1.YieldFromTransformer(str_0)
    dict_0 = {str_0: yield_from_transformer_0, str_0: str_0}
    interactive_0 = module_0.Interactive(*dict_0, **dict_0)
    a_s_t_0 = yield_from_transformer_0.visit(interactive_0)
