# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import sanic.errorpages as module_1
import inspect as module_2


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    bool_0 = False
    config_0 = module_0.Config(bool_0, keep_alive=bool_0)


def test_case_2():
    none_type_0 = None
    config_0 = module_0.Config(
        none_type_0, none_type_0, none_type_0, converters=none_type_0
    )
    complex_0 = -1646.8 + 1665.3j
    module_1.check_error_format(complex_0)


def test_case_3():
    int_0 = -74
    bool_0 = True
    module_0.Config(int_0, keep_alive=bool_0)


def test_case_4():
    config_0 = module_0.Config()
    var_0 = module_2.getmembers(config_0)
    config_0.update_config(var_0)


def test_case_5():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_6():
    config_0 = module_0.Config()
    none_type_0 = config_0.register_type(config_0)
    none_type_1 = config_0.update()
    config_0.update_config(none_type_0)


def test_case_7():
    str_0 = "w^kATV\x0cE6^"
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=none_type_0, converters=none_type_0)
    var_0 = config_0.load_environment_vars()
    none_type_1 = config_0.__setitem__(str_0, str_0)
    none_type_2 = None
    config_1 = module_0.Config(keep_alive=none_type_2)
    none_type_3 = config_1.update(**config_1)
    none_type_4 = config_0.register_type(none_type_2)


def test_case_8():
    none_type_0 = None
    bool_0 = True
    config_0 = module_0.Config(keep_alive=none_type_0)
    config_1 = module_0.Config(none_type_0, keep_alive=bool_0)
    config_0.__getattr__(config_0)


def test_case_9():
    bool_0 = True
    module_0.Config(keep_alive=bool_0, converters=bool_0)


def test_case_10():
    none_type_0 = None
    bool_0 = True
    module_0.Config(env_prefix=bool_0, converters=none_type_0)


def test_case_11():
    none_type_0 = None
    bool_0 = True
    config_0 = module_0.Config(keep_alive=none_type_0)
    config_1 = module_0.Config(none_type_0, keep_alive=bool_0)
    none_type_1 = config_1.register_type(none_type_0)
    bytes_0 = b"Unauthorized"
    config_0.update_config(bytes_0)


def test_case_12():
    none_type_0 = None
    bool_0 = True
    config_0 = module_0.Config(keep_alive=none_type_0)
    config_1 = module_0.Config(none_type_0, keep_alive=bool_0)
    none_type_1 = config_1.register_type(none_type_0)
    config_1.register_type(none_type_1)


def test_case_13():
    str_0 = "w^kATV\x0cE6^"
    module_0.Config(keep_alive=str_0, converters=str_0)


def test_case_14():
    str_0 = "%\t"
    int_0 = -2520
    tuple_0 = (str_0, int_0)
    config_0 = module_0.Config(converters=tuple_0)
    none_type_0 = None
    bool_0 = True
    config_1 = module_0.Config(keep_alive=none_type_0)
    none_type_1 = config_1.update(**config_1)
    config_1.update_config(bool_0)


def test_case_15():
    str_0 = ""
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=none_type_0, converters=none_type_0)
    none_type_1 = config_0.__setitem__(str_0, str_0)
    none_type_2 = config_0.update(**config_0)
    config_0.load_environment_vars(str_0)


def test_case_16():
    str_0 = "w^kATV\x0cE6^"
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=none_type_0, converters=none_type_0)
    none_type_1 = config_0.update()
    config_1 = module_0.Config(none_type_0)
    none_type_2 = config_1.update(**config_0)
    none_type_3 = None
    config_2 = module_0.Config(keep_alive=none_type_3)
    config_3 = module_0.Config(none_type_0, keep_alive=none_type_3)
    str_1 = "LOCAL_CERT_CREATOR"
    config_2.__setitem__(str_1, str_0)


def test_case_17():
    str_0 = "w^kATV\x0cE6^"
    str_1 = "_FALLBACK_ERROR_FORMAT"
    float_0 = 2188.0
    dict_0 = {str_1: str_0, str_0: float_0, str_0: str_1}
    none_type_0 = None
    module_0.Config(dict_0, none_type_0)
