# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.base as module_1


def test_case_0():
    mod_0 = module_0.mod()
    base_import_rewrite_0 = module_1.BaseImportRewrite(mod_0)


def test_case_1():
    add_0 = module_0.Add()
    none_type_0 = None
    base_node_transformer_0 = module_1.BaseNodeTransformer(add_0)
    base_node_transformer_1 = module_1.BaseNodeTransformer(add_0)
    base_import_rewrite_0 = module_1.BaseImportRewrite(base_node_transformer_1)
    base_node_transformer_2 = module_1.BaseNodeTransformer(add_0)
    base_import_rewrite_1 = module_1.BaseImportRewrite(add_0)
    list_0 = [none_type_0]
    dict_0 = {}
    import_from_0 = module_0.ImportFrom(*list_0, **dict_0)
    base_import_rewrite_1.visit_ImportFrom(import_from_0)


def test_case_2():
    add_0 = module_0.Add()
    base_import_rewrite_0 = module_1.BaseImportRewrite(add_0)
    list_0 = []
    dict_0 = {}
    list_1 = [list_0, list_0, add_0]
    import_from_0 = module_0.ImportFrom(*list_1, **dict_0)
    var_0 = base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_3():
    add_0 = module_0.Add()
    base_import_rewrite_0 = module_1.BaseImportRewrite(add_0)
    list_0 = [base_import_rewrite_0]
    list_1 = [list_0, list_0, add_0]
    import_from_0 = module_0.ImportFrom(*list_1)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)
