# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.base as module_1
import typed_ast.ast3 as module_2


def test_case_0():
    str_0 = module_0.Str()
    base_node_transformer_0 = module_1.BaseNodeTransformer(str_0)


def test_case_1():
    operator_0 = module_0.operator()
    list_0 = [operator_0, operator_0, operator_0]
    base_import_rewrite_0 = module_1.BaseImportRewrite(list_0)
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_2():
    operator_0 = module_0.operator()
    var_0 = module_2.walk(operator_0)
    list_0 = [operator_0, var_0, operator_0]
    base_import_rewrite_0 = module_1.BaseImportRewrite(list_0)
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_3():
    operator_0 = module_0.operator()
    var_0 = module_2.iter_child_nodes(operator_0)
    list_0 = [operator_0, var_0, operator_0]
    base_import_rewrite_0 = module_1.BaseImportRewrite(list_0)
    import_from_0 = module_0.ImportFrom(*list_0)
    var_1 = base_import_rewrite_0.visit_ImportFrom(import_from_0)
