# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_1():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    bool_0 = immutable_list_0.__eq__(var_0)
    immutable_list_0.filter(var_0)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_1)


def test_case_3():
    float_0 = -1333.03
    int_0 = 0
    tuple_0 = (int_0,)
    float_1 = -440.0
    tuple_1 = (float_1,)
    immutable_list_0 = module_0.ImmutableList(tail=tuple_1)
    immutable_list_1 = immutable_list_0.unshift(tuple_0)
    immutable_list_1.__add__(float_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_1.find(var_0)


def test_case_5():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_1.__len__()
    var_1 = immutable_list_0.__len__()
    immutable_list_1.find(var_1)


def test_case_6():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0, none_type_0)
    str_0 = immutable_list_0.__str__()


def test_case_7():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_1.to_list()
    var_1 = immutable_list_0.__len__()
    immutable_list_1.find(var_1)


def test_case_8():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_0 = immutable_list_1.find(immutable_list_1)
    immutable_list_2 = immutable_list_0.unshift(immutable_list_0)
    var_1 = immutable_list_0.to_list()
    bool_0 = var_1.__eq__(immutable_list_2)
    immutable_list_0.map(immutable_list_2)


def test_case_9():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(tail=bool_0)
    immutable_list_1 = immutable_list_0.append(bool_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_1.map(var_0)


def test_case_10():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_0 = immutable_list_0.find(immutable_list_0)
    var_1 = immutable_list_0.reduce(immutable_list_0, var_0)
    immutable_list_1.filter(var_1)


def test_case_12():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()
    str_0 = immutable_list_0.__str__()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = immutable_list_0.unshift(immutable_list_1)
    var_0 = immutable_list_0.__len__()
    var_1 = immutable_list_0.reduce(var_0, var_0)
    var_2 = immutable_list_1.to_list()
    immutable_list_3 = var_1.__add__(var_2)
    str_1 = immutable_list_0.__str__()
    immutable_list_2.reduce(var_1, immutable_list_0)


def test_case_15():
    immutable_list_0 = module_0.ImmutableList()


def test_case_16():
    complex_0 = -1473 - 1455.44496j
    immutable_list_0 = module_0.ImmutableList(complex_0)
    immutable_list_0.find(complex_0)


def test_case_17():
    float_0 = -2820.265
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(float_0, is_empty=bool_0)
    none_type_0 = None
    immutable_list_0.reduce(none_type_0, none_type_0)


def test_case_18():
    complex_0 = -1473 - 1455.44496j
    immutable_list_0 = module_0.ImmutableList(complex_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.find(complex_0)


def test_case_19():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    var_1 = immutable_list_0.find(immutable_list_0)
    var_2 = immutable_list_0.reduce(immutable_list_0, var_1)
    immutable_list_0.filter(var_1)


def test_case_20():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    bool_0 = immutable_list_0.__eq__(immutable_list_1)
    immutable_list_1.find(var_0)
