# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    str_0 = " "
    module_0.Config(str_0, keep_alive=str_0, converters=str_0)


def test_case_2():
    none_type_0 = None
    config_0 = module_0.Config(converters=none_type_0)
    list_0 = module_1.getmembers(config_0)
    config_1 = module_0.Config(none_type_0, none_type_0, converters=none_type_0)


def test_case_3():
    str_0 = "\r"
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, keep_alive=str_0, converters=str_0)
    config_0.update_config(none_type_0)


def test_case_4():
    str_0 = " "
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=str_0)
    config_0.update_config(none_type_0)


def test_case_5():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_6():
    config_0 = module_0.Config()
    none_type_0 = config_0.register_type(config_0)
    none_type_1 = config_0.update()
    config_0.register_type(config_0)


def test_case_7():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0)


def test_case_8():
    config_0 = module_0.Config()
    config_0.__getattr__(config_0)


def test_case_9():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0)
    str_0 = "L"
    var_0 = config_0.load_environment_vars(str_0)
    str_1 = "0Bi"
    var_1 = module_1.isclass(str_0)
    none_type_1 = None
    config_1 = module_0.Config(none_type_1)
    config_1.update_config(str_1)


def test_case_10():
    str_0 = " "
    none_type_0 = None
    config_0 = module_1.getmembers(str_0)
    module_0.Config(env_prefix=config_0, converters=none_type_0)


def test_case_11():
    config_0 = module_0.Config()
    none_type_0 = None
    config_0.update_config(none_type_0)


def test_case_12():
    str_0 = ""
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0)
    config_0.load_environment_vars(str_0)
