# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1
import sanic.http.http1 as module_2
import sanic.errorpages as module_3


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    int_0 = 200
    module_0.Config(keep_alive=int_0, converters=int_0)


def test_case_2():
    bool_0 = True
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=none_type_0, keep_alive=bool_0)
    config_0.update_config(none_type_0)


def test_case_3():
    bool_0 = True
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=none_type_0, keep_alive=none_type_0)
    none_type_1 = config_0.register_type(bool_0)


def test_case_4():
    bool_0 = True
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=none_type_0, keep_alive=bool_0)
    none_type_1 = module_1.getmembers(config_0)
    config_0.update_config(none_type_0)


def test_case_5():
    bytes_0 = b"Reset Content"
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, keep_alive=none_type_0)
    config_0.update_config(bytes_0)


def test_case_6():
    str_0 = "W$%*9kcUr.O&[H"
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=str_0, keep_alive=none_type_0)
    float_0 = -4401.823734
    module_2.Http(float_0)


def test_case_7():
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=none_type_0, keep_alive=none_type_0)
    config_0.__setitem__(none_type_0, config_0)


def test_case_8():
    str_0 = "xCyui8"
    dict_0 = {str_0: str_0, str_0: str_0}
    config_0 = module_0.Config(dict_0)
    none_type_0 = config_0.register_type(dict_0)
    config_1 = module_0.Config(dict_0)
    none_type_1 = config_1.update()
    config_1.__setitem__(config_1, str_0)


def test_case_9():
    config_0 = module_0.Config()
    none_type_0 = config_0.update_config(config_0)


def test_case_10():
    none_type_0 = None
    config_0 = module_0.Config()
    config_0.update_config(none_type_0)


def test_case_11():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0)
    config_0.__getattr__(config_0)


def test_case_12():
    str_0 = "xCyui8"
    dict_0 = {str_0: str_0, str_0: str_0}
    config_0 = module_0.Config(dict_0)
    config_1 = module_0.Config(keep_alive=config_0, converters=config_0)
    none_type_0 = config_0.register_type(dict_0)
    config_2 = module_0.Config(dict_0)
    module_3.check_error_format(dict_0)


def test_case_13():
    str_0 = "KuP"
    str_1 = "`x>>(A"
    dict_0 = {str_1: str_1}
    module_0.Config(dict_0, keep_alive=str_0, converters=str_1)


def test_case_14():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0)
    var_0 = config_0.update_config(config_0)
    str_0 = "LOCAL_CERT_CREATOR"
    config_0.__setattr__(str_0, str_0)


def test_case_15():
    str_0 = ""
    config_0 = module_0.Config(str_0)
    config_0.load_environment_vars(str_0)
