# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    str_0 = "k*F'vU W?oPZ@&="
    immutable_list_0 = module_0.ImmutableList(str_0, str_0, str_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    immutable_list_0.find(immutable_list_0)


def test_case_1():
    str_0 = "l|71QF6FVuHm,:bRs@w"
    immutable_list_0 = module_0.ImmutableList(str_0, str_0, str_0)
    bool_0 = immutable_list_0.__eq__(str_0)
    immutable_list_0.find(bool_0)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.append(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_3():
    str_0 = "3I>Y}Xz*\nn_R:"
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0, none_type_0)
    immutable_list_0.__add__(str_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    str_0 = immutable_list_1.__len__()
    immutable_list_1.find(immutable_list_0)


def test_case_5():
    str_0 = "!25tnYd@_w_`*KGY%%\r"
    immutable_list_0 = module_0.ImmutableList(str_0, str_0, str_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.find(immutable_list_0)


def test_case_6():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    immutable_list_0.filter(immutable_list_0)


def test_case_7():
    float_0 = -1950.7
    immutable_list_0 = module_0.ImmutableList(tail=float_0)
    immutable_list_0.to_list()


def test_case_8():
    float_0 = 509.291
    immutable_list_0 = module_0.ImmutableList(float_0)
    immutable_list_0.map(immutable_list_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    none_type_0 = None
    immutable_list_1 = immutable_list_0.unshift(none_type_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_1)
    immutable_list_2 = immutable_list_0.unshift(immutable_list_1)
    none_type_1 = None
    immutable_list_3 = immutable_list_0.append(immutable_list_0)
    immutable_list_4 = immutable_list_2.unshift(none_type_1)
    immutable_list_5 = module_0.ImmutableList(none_type_1)
    immutable_list_6 = module_0.ImmutableList(none_type_1)
    immutable_list_7 = immutable_list_6.__add__(immutable_list_3)
    immutable_list_8 = immutable_list_5.unshift(immutable_list_0)
    var_0 = immutable_list_4.reduce(immutable_list_5, immutable_list_5)
    immutable_list_4.map(var_0)


def test_case_10():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__add__(immutable_list_0)
    var_0.filter(immutable_list_0)


def test_case_12():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_13():
    str_0 = "k*F'vU W?oPZ@&="
    immutable_list_0 = module_0.ImmutableList(str_0, str_0, str_0)
    immutable_list_0.find(immutable_list_0)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = module_0.ImmutableList()
    var_0 = immutable_list_1.reduce(immutable_list_0, immutable_list_0)
    var_1 = immutable_list_0.reduce(var_0, var_0)


def test_case_15():
    immutable_list_0 = module_0.ImmutableList()


def test_case_16():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.unshift(immutable_list_0)
    str_0 = var_0.__str__()
    var_0.find(immutable_list_0)


def test_case_17():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_18():
    str_0 = "g25tnYd@4w*KGY%%\r"
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(str_0)
    immutable_list_2 = immutable_list_1.append(str_0)
    immutable_list_1.find(immutable_list_2)


def test_case_19():
    str_0 = "!25tnYd@_w_`-KGY%%\r"
    immutable_list_0 = module_0.ImmutableList(str_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.find(var_0)


def test_case_20():
    str_0 = "l|71QF6FVuHm,:bRs@w"
    immutable_list_0 = module_0.ImmutableList(str_0)
    none_type_0 = None
    immutable_list_0.find(none_type_0)


def test_case_21():
    none_type_0 = None
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(none_type_0, bool_0, bool_0)
    immutable_list_1 = immutable_list_0.append(none_type_0)
    var_0 = immutable_list_0.find(bool_0)
    immutable_list_2 = module_0.ImmutableList()
    var_1 = immutable_list_2.reduce(var_0, var_0)
    bool_1 = immutable_list_2.__eq__(immutable_list_1)
    immutable_list_1.filter(var_0)


def test_case_22():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0)
    immutable_list_0.reduce(bool_0, bool_0)


def test_case_23():
    complex_0 = 2064.039996 - 771.89127j
    list_0 = []
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    immutable_list_1 = immutable_list_0.unshift(list_0)
    immutable_list_2 = immutable_list_1.unshift(complex_0)
    immutable_list_1.reduce(immutable_list_2, immutable_list_2)


def test_case_24():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_1)
    immutable_list_1.find(immutable_list_1)
