# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import flutils.setuputils.cmd as module_0


def test_case_0():
    str_0 = "ABHGrQRld-6=x\tJ)|"
    module_0.build_setup_cfg_command_class(str_0)
