# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.transformers.dict_unpacking as module_0
import typed_ast._ast3 as module_1


def test_case_0():
    none_type_0 = None
    dict_unpacking_transformer_0 = module_0.DictUnpackingTransformer(none_type_0)


def test_case_1():
    function_def_0 = module_1.FunctionDef()
    dict_unpacking_transformer_0 = module_0.DictUnpackingTransformer(function_def_0)
    bool_0 = True
    dict_unpacking_transformer_0.visit_Module(bool_0)
