# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.validation as module_0
import builtins as module_1


def test_case_0():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    var_0 = validation_0.__eq__(validation_0)


def test_case_1():
    str_0 = "B\x0bGxMeq(P,"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_maybe()
    var_1 = validation_0.is_success()
    var_2 = validation_0.__str__()
    var_3 = validation_0.__eq__(var_2)
    var_1.to_box()


def test_case_2():
    str_0 = "B\x0bGxMeq(P,"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_maybe()
    var_1 = validation_0.__str__()
    var_2 = validation_0.__eq__(validation_0)
    validation_1 = module_0.Validation(validation_0, var_1)
    var_1.to_try()


def test_case_3():
    str_0 = "CKX0BnJI"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.__eq__(validation_0)
    var_1 = validation_0.to_either()


def test_case_4():
    str_0 = "B\x0bGxMeq(P,"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_maybe()
    var_1 = var_0.to_box()
    var_2 = validation_0.is_fail()
    var_1.to_box()


def test_case_5():
    float_0 = 347.82
    validation_0 = module_0.Validation(float_0, float_0)


def test_case_6():
    int_0 = -2181
    none_type_0 = None
    validation_0 = module_0.Validation(int_0, none_type_0)
    validation_0.__str__()


def test_case_7():
    object_0 = module_1.object()
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    validation_0.is_fail()


def test_case_8():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    validation_0.map(validation_0)


def test_case_9():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    var_0 = validation_0.__eq__(validation_0)
    validation_0.bind(var_0)


def test_case_10():
    str_0 = "CKX0BnJI"
    validation_0 = module_0.Validation(str_0, str_0)
    validation_1 = module_0.Validation(str_0, str_0)
    validation_1.ap(validation_1)


def test_case_11():
    str_0 = "B\x0bGxMeq(P,"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_maybe()
    var_1 = validation_0.to_box()
    var_2 = var_0.to_box()
    var_3 = validation_0.is_fail()
    var_2.is_success()


def test_case_12():
    dict_0 = {}
    validation_0 = module_0.Validation(dict_0, dict_0)
    var_0 = validation_0.to_lazy()
    var_1 = validation_0.to_either()
    var_1.to_either()


def test_case_13():
    bytes_0 = b"\xd3}\xead\xb9kJbeL\xb7Nt\x82zV"
    bool_0 = True
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.to_lazy()
    var_1 = var_0.bind(bool_0)
    var_1.to_box()


def test_case_14():
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    var_0 = validation_0.__eq__(validation_0)
    validation_0.to_try()


def test_case_15():
    str_0 = "CKX0BnJI"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.__str__()
    var_1 = validation_0.is_fail()
    var_2 = var_1.__eq__(var_1)
    validation_1 = module_0.Validation(str_0, var_2)
    var_3 = validation_1.__eq__(validation_0)
    var_4 = var_2.__eq__(validation_0)
    validation_1.to_either()


def test_case_16():
    set_0 = set()
    validation_0 = module_0.Validation(set_0, set_0)
    var_0 = validation_0.to_lazy()
    var_1 = validation_0.to_maybe()
    var_2 = validation_0.__str__()
    validation_1 = module_0.Validation(var_0, set_0)
    var_3 = validation_1.to_either()
    validation_1.bind(var_2)
