# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import flutils.namedtupleutils as module_0
import collections as module_1


def test_case_0():
    int_0 = 3819
    module_0.to_namedtuple(int_0)


def test_case_1():
    str_0 = "@wkZ\\i!`5\rOU)An"
    int_0 = 2929
    tuple_0 = (str_0, int_0, int_0)
    var_0 = module_0.to_namedtuple(tuple_0)


def test_case_2():
    none_type_0 = None
    str_0 = "Y"
    dict_0 = {
        str_0: none_type_0,
        str_0: none_type_0,
        str_0: none_type_0,
        str_0: none_type_0,
    }
    var_0 = module_0.to_namedtuple(dict_0)
    var_1 = module_0.to_namedtuple(var_0)


def test_case_3():
    list_0 = []
    ordered_dict_0 = module_1.OrderedDict(*list_0)
    var_0 = module_0.to_namedtuple(ordered_dict_0)


def test_case_4():
    str_0 = 'cT~x-\x0b"5'
    module_0.to_namedtuple(str_0)


def test_case_5():
    list_0 = []
    var_0 = module_0.to_namedtuple(list_0)


def test_case_6():
    ordered_dict_0 = module_1.OrderedDict()
    var_0 = module_0.to_namedtuple(ordered_dict_0)
    dict_0 = {var_0: var_0, var_0: var_0}
    var_1 = module_0.to_namedtuple(dict_0)
    var_2 = module_0.to_namedtuple(var_0)
    var_3 = module_0.to_namedtuple(dict_0)


def test_case_7():
    str_0 = "is_package"
    list_0 = [str_0]
    var_0 = module_0.to_namedtuple(list_0)


def test_case_8():
    list_0 = []
    ordered_dict_0 = module_1.OrderedDict(*list_0)
    var_0 = module_0.to_namedtuple(ordered_dict_0)
    var_1 = module_0.to_namedtuple(var_0)


def test_case_9():
    tuple_0 = ()
    var_0 = module_0.to_namedtuple(tuple_0)


def test_case_10():
    none_type_0 = None
    str_0 = ""
    str_1 = "Y"
    dict_0 = {
        str_1: none_type_0,
        str_0: none_type_0,
        str_0: none_type_0,
        str_1: none_type_0,
    }
    var_0 = module_0.to_namedtuple(dict_0)
    var_1 = module_0.to_namedtuple(var_0)


def test_case_11():
    bytes_0 = b"y\xce\x06\xbc\xc5\xee\xfe\xac\xa2yD\xdeX\xa6\xee="
    dict_0 = {bytes_0: bytes_0}
    tuple_0 = (dict_0,)
    module_0.to_namedtuple(tuple_0)


def test_case_12():
    bool_0 = True
    bytes_0 = b"\\Ws\xa0\xf5\xe0A\xd8pJ"
    list_0 = [bool_0, bytes_0]
    var_0 = module_0.to_namedtuple(list_0)
    none_type_0 = None
    str_0 = ""
    str_1 = "u\r"
    str_2 = "QtCq*\x0b~>'iL~"
    dict_0 = {
        str_2: none_type_0,
        str_0: none_type_0,
        str_1: none_type_0,
        str_2: none_type_0,
    }
    var_1 = module_0.to_namedtuple(dict_0)
    var_2 = module_0.to_namedtuple(var_1)
    module_0.to_namedtuple(str_1)
