# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis.builtins.da as module_0


def test_case_0():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()


def test_case_1():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.__str__()
    str_1 = denmark_spec_provider_0.cpr()
    str_2 = denmark_spec_provider_0.cpr()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()
    str_3 = denmark_spec_provider_1.cpr()
    denmark_spec_provider_2 = module_0.DenmarkSpecProvider(str_2)
    str_4 = denmark_spec_provider_2.cpr()
    str_5 = denmark_spec_provider_0.cpr()
    str_6 = denmark_spec_provider_1.cpr()
    denmark_spec_provider_3 = module_0.DenmarkSpecProvider()


def test_case_2():
    bool_0 = False
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()
    none_type_0 = None
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider(bool_0)
    str_1 = denmark_spec_provider_0.cpr()
    denmark_spec_provider_1.validate_enum(bool_0, none_type_0)


def test_case_3():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()


def test_case_4():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    int_0 = -651
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider(int_0)
    str_0 = denmark_spec_provider_1.cpr()
    none_type_0 = None
    generator_0 = denmark_spec_provider_0.override_locale(none_type_0)
    str_1 = denmark_spec_provider_0.cpr()
    str_2 = denmark_spec_provider_0.cpr()


def test_case_5():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()


def test_case_6():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()
    denmark_spec_provider_2 = module_0.DenmarkSpecProvider()
    denmark_spec_provider_3 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_3.cpr()
    denmark_spec_provider_4 = module_0.DenmarkSpecProvider()
    float_0 = 1634.76637
    denmark_spec_provider_5 = module_0.DenmarkSpecProvider(float_0)
