# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0
import contextlib as module_1


def test_case_0():
    timer_0 = module_0.Timer()


def test_case_1():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    none_type_1 = timer_0.start()
    var_0 = timer_0.__call__(none_type_1)
    list_0 = [none_type_1]
    var_1 = timer_1.__eq__(list_0)
    float_arg_0 = module_0.FloatArg()
    timer_0.start()


def test_case_2():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()


def test_case_3():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    none_type_1 = timer_0.start()
    timer_2 = module_0.Timer(none_type_0, none_type_0)
    timer_2.stop()


def test_case_4():
    bytes_0 = b"\xc2"
    none_type_0 = None
    timer_0 = module_0.Timer(bytes_0, logger=none_type_0)
    timer_1 = timer_0.__enter__()
    none_type_1 = timer_1.__exit__()
    var_0 = timer_0.__repr__()
    var_1 = var_0.__len__()
    none_type_2 = timer_1.start()


def test_case_5():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    none_type_1 = timer_0.start()
    timer_2 = module_0.Timer()
    float_arg_0 = module_0.FloatArg()
    timer_3 = module_0.Timer(none_type_0, initial_text=float_arg_0)
    timer_4 = timer_3.__enter__()


def test_case_6():
    timer_0 = module_0.Timer()
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_1.__exit__()
    none_type_1 = timer_0.start()
    str_0 = "2K"
    timer_2 = module_0.Timer(text=none_type_0, initial_text=str_0)
    float_0 = timer_1.stop()
    timer_3 = timer_2.__enter__()
    var_0 = timer_2.__repr__()
    timer_0.__exit__()


def test_case_7():
    bytes_0 = b"\xf5\xe4"
    context_decorator_0 = module_1.ContextDecorator()
    var_0 = context_decorator_0.__call__(bytes_0)
    timer_0 = module_0.Timer(initial_text=var_0)
    timer_1 = module_0.Timer(context_decorator_0, bytes_0, var_0)
    none_type_0 = timer_0.start()
    none_type_1 = timer_1.start()
    float_0 = timer_0.stop()
    timer_error_0 = module_0.TimerError()
    var_0.__enter__()
