# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    none_type_0 = None
    config_0 = module_0.Config(
        none_type_0, none_type_0, none_type_0, converters=none_type_0
    )


def test_case_2():
    float_0 = 6.18084
    module_0.Config(float_0)


def test_case_3():
    config_0 = module_0.Config()
    var_0 = module_1.getmembers(config_0)


def test_case_4():
    str_0 = "YM[9[0L\n'"
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=str_0, keep_alive=none_type_0)


def test_case_5():
    config_0 = module_0.Config()
    str_0 = "1oU"
    none_type_0 = config_0.register_type(str_0)
    var_0 = config_0.update_config(config_0)
    var_1 = config_0.update_config(config_0)


def test_case_6():
    float_0 = 2293.469215632248
    str_0 = "YM9[40L"
    config_0 = module_0.Config(keep_alive=float_0, converters=str_0)
    config_0.update_config(float_0)


def test_case_7():
    bytes_0 = b"'5\xa2\x86]+%\xac\xca\xb7\xac\xb3q\x13"
    none_type_0 = None
    module_0.Config(none_type_0, converters=bytes_0)


def test_case_8():
    bytes_0 = b"'5\xa2\x86]+%\xac\xca\xb7\xac\xb3q\x13"
    config_0 = module_0.Config(keep_alive=bytes_0)


def test_case_9():
    str_0 = "YM[9[0L\n'"
    none_type_0 = None
    config_0 = module_0.Config(env_prefix=none_type_0)
    config_0.update_config(str_0)


def test_case_10():
    bytes_0 = b"2\xa2g.\xe1\x7fu\xcd\r\x99\xa9\xda\x0b\x9az\x95\x01\xd9"
    bytes_1 = b"'5\xa2\x86]+%\xac\xca\xb7\xac\xb3q\x13"
    config_0 = module_0.Config(keep_alive=bytes_1, converters=bytes_0)
    config_0.__getattr__(config_0)


def test_case_11():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_12():
    none_type_0 = None
    config_0 = module_0.Config(
        none_type_0, none_type_0, none_type_0, converters=none_type_0
    )
    config_0.update_config(none_type_0)


def test_case_13():
    float_0 = 2293.469215632248
    str_0 = "YM9[40L"
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=float_0, converters=str_0)
    none_type_1 = config_0.__setitem__(str_0, none_type_0)
    config_0.update_config(none_type_0)


def test_case_14():
    float_0 = 2293.469215632248
    str_0 = "YM9[40L"
    none_type_0 = None
    int_0 = -365
    str_1 = "LOCAL_CERT_CREATOR"
    dict_0 = {
        str_0: int_0,
        str_0: int_0,
        str_1: str_0,
        str_1: float_0,
        str_0: str_0,
        str_1: float_0,
    }
    bool_0 = True
    config_0 = module_0.Config(dict_0, keep_alive=bool_0, converters=none_type_0)
    config_0.update(**dict_0)


def test_case_15():
    float_0 = 2869.425054443492
    str_0 = ""
    config_0 = module_0.Config(keep_alive=float_0, converters=str_0)
    none_type_0 = config_0.update(**config_0)
    config_0.load_environment_vars(str_0)
