# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    str_0 = "hs''"
    dict_0 = {str_0: str_0, str_0: str_0}
    module_0.Config(dict_0, str_0, converters=str_0)


def test_case_2():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0)
    config_0.update_config(none_type_0)


def test_case_3():
    config_0 = module_0.Config()
    config_0.log_response()


def test_case_4():
    config_0 = module_0.Config()
    none_type_0 = None
    config_0.update_config(none_type_0)


def test_case_5():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)


def test_case_6():
    bool_0 = True
    config_0 = module_0.Config(keep_alive=bool_0)
    bool_0.__setitem__(config_0, bool_0)


def test_case_7():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0)
    var_0 = config_0.load_environment_vars()
    config_0.__getattr__(config_0)


def test_case_8():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, none_type_0, none_type_0)
    config_0.__setitem__(none_type_0, none_type_0)


def test_case_9():
    none_type_0 = None
    config_0 = module_0.Config(keep_alive=none_type_0)
    var_0 = config_0.load_environment_vars()
    module_0.Config(env_prefix=config_0, keep_alive=none_type_0, converters=config_0)


def test_case_10():
    bool_0 = False
    config_0 = module_0.Config(converters=bool_0)
    none_type_0 = config_0.update()
    var_0 = config_0.load_environment_vars()
    str_0 = "gucj#\x0b"
    config_0.update_config(str_0)
