# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import builtins as module_1
import inspect as module_2


def test_case_0():
    bool_0 = module_0.is_atty()
    var_0 = module_0.has_message_body(bool_0)


def test_case_1():
    bytes_0 = b"\x9a1\xc9\xc5\xb8\xd7\xc1"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    bool_0 = True
    module_0.is_hop_by_hop_header(bool_0)


def test_case_4():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()


def test_case_5():
    float_0 = 212.4
    var_0 = module_0.has_message_body(float_0)
    module_0.is_hop_by_hop_header(float_0)


def test_case_6():
    bool_0 = module_0.is_atty()
    bytes_0 = b"\xde\xcd(\x9f\x84"
    var_0 = bytes_0.__repr__()
    str_0 = var_0.__str__()
    dict_0 = {
        bytes_0: bytes_0,
        bytes_0: bytes_0,
        var_0: var_0,
        var_0: var_0,
        bytes_0: bytes_0,
    }
    var_1 = module_0.is_hop_by_hop_header(bytes_0)
    object_0 = module_1.object()
    var_2 = module_0.remove_entity_headers(dict_0)
    var_3 = var_2.__repr__()
    var_4 = var_3.__repr__()
    var_5 = var_3.__repr__()
    var_6 = module_0.has_message_body(bool_0)
    default_0 = module_0.Default()
    var_7 = default_0.__repr__()
    var_8 = module_2.ismodule(var_1)
    int_0 = 304
    var_9 = module_0.has_message_body(int_0)
    bool_1 = module_0.is_atty()
    object_1 = module_1.object()
    object_2 = module_1.object()
    str_1 = var_5.__str__()
    var_10 = module_0.is_entity_header(str_0)
