# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)


def test_case_1():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = immutable_list_0.__add__(immutable_list_1)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_3 = module_0.ImmutableList(immutable_list_2, var_0)
    immutable_list_3.find(var_0)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_1 = immutable_list_0.append(immutable_list_0)
    str_0 = immutable_list_0.__str__()
    var_0.to_list()


def test_case_3():
    tuple_0 = ()
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.__add__(tuple_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__len__()
    var_1 = immutable_list_0.find(var_0)
    immutable_list_0.filter(var_1)


def test_case_5():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(bool_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.filter(var_0)


def test_case_6():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_2 = immutable_list_1.to_list()
    immutable_list_1.find(immutable_list_1)


def test_case_7():
    int_0 = 997
    dict_0 = {int_0: int_0, int_0: int_0}
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.append(dict_0)
    str_0 = "$8P00\\[L\tT( V,Tr"
    immutable_list_2 = module_0.ImmutableList()
    immutable_list_3 = immutable_list_2.append(str_0)
    immutable_list_4 = immutable_list_3.unshift(immutable_list_1)
    none_type_0 = None
    immutable_list_5 = module_0.ImmutableList(tail=none_type_0)
    var_0 = immutable_list_2.find(str_0)
    var_1 = immutable_list_5.__len__()
    immutable_list_5.map(var_1)


def test_case_8():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    var_1 = immutable_list_0.find(var_0)
    var_2 = immutable_list_0.reduce(var_1, immutable_list_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_3 = immutable_list_1.__len__()
    immutable_list_1.filter(immutable_list_1)


def test_case_10():
    bool_0 = False
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(is_empty=none_type_0)
    none_type_1 = None
    immutable_list_1 = module_0.ImmutableList(none_type_1, is_empty=none_type_1)
    var_0 = immutable_list_1.reduce(bool_0, bool_0)


def test_case_11():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0, is_empty=bool_0)
    var_0 = immutable_list_0.__len__()
    var_1 = immutable_list_0.__len__()
    immutable_list_0.reduce(var_0, bool_0)


def test_case_12():
    immutable_list_0 = module_0.ImmutableList()


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_1)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_1.find(immutable_list_1)


def test_case_15():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    none_type_0 = None
    bool_0 = immutable_list_0.__eq__(none_type_0)
    immutable_list_2 = immutable_list_0.__add__(immutable_list_0)
    var_0 = immutable_list_1.to_list()
    var_1 = immutable_list_0.__len__()
    var_2 = immutable_list_2.__len__()
    immutable_list_3 = immutable_list_0.append(none_type_0)
    var_3 = immutable_list_0.find(var_2)
    var_4 = immutable_list_0.to_list()
    immutable_list_1.map(var_0)


def test_case_16():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(bool_0)
    immutable_list_0.find(immutable_list_0)


def test_case_17():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_2 = immutable_list_1.append(immutable_list_0)
    immutable_list_3 = var_0.__add__(immutable_list_1)
    immutable_list_4 = immutable_list_0.__add__(var_0)
    immutable_list_5 = immutable_list_0.__add__(immutable_list_0)
    var_1 = immutable_list_0.__len__()
    immutable_list_6 = module_0.ImmutableList(var_0, immutable_list_5)
    immutable_list_6.find(var_1)


def test_case_18():
    tuple_0 = ()
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0, bool_0)
    immutable_list_0.find(tuple_0)


def test_case_19():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_2 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_1.find(immutable_list_1)


def test_case_20():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    var_1 = immutable_list_0.reduce(var_0, immutable_list_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    bool_0 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_2 = immutable_list_0.__add__(immutable_list_0)
    var_2 = immutable_list_0.__len__()
    immutable_list_3 = immutable_list_0.append(var_0)
    var_3 = immutable_list_3.find(var_2)
    immutable_list_4 = module_0.ImmutableList(immutable_list_0, bool_0, var_1)
    immutable_list_4.reduce(var_0, immutable_list_0)
