# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(is_empty=bool_0)
    bool_1 = immutable_list_0.__eq__(immutable_list_0)


def test_case_1():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList()
    bool_1 = immutable_list_0.__eq__(bool_0)
    immutable_list_1 = module_0.ImmutableList()
    immutable_list_2 = immutable_list_1.unshift(bool_0)
    immutable_list_2.find(bool_1)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_3():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    immutable_list_0.__add__(var_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_1.find(immutable_list_0)


def test_case_5():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    str_0 = immutable_list_0.__str__()
    immutable_list_1.find(immutable_list_0)


def test_case_6():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    str_0 = immutable_list_1.__str__()
    immutable_list_1.find(immutable_list_0)


def test_case_7():
    str_0 = 'y&"[7a&\t\nmY'
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.map(str_0)


def test_case_8():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.__len__()
    immutable_list_1 = immutable_list_0.append(immutable_list_0)
    var_1 = immutable_list_0.__len__()
    immutable_list_1.map(var_1)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_10():
    int_0 = 4822
    dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0}
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()
    immutable_list_1 = module_0.ImmutableList(tail=var_0)
    immutable_list_1.filter(dict_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    var_1 = immutable_list_0.reduce(var_0, var_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_12():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.unshift(immutable_list_0)
    str_0 = var_0.__str__()
    var_1 = immutable_list_0.reduce(var_0, immutable_list_0)
    var_2 = var_0.__len__()
    var_0.reduce(var_2, str_0)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()


def test_case_15():
    bool_0 = False
    none_type_0 = None
    bool_1 = False
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0, is_empty=bool_1)
    immutable_list_1 = immutable_list_0.append(bool_0)


def test_case_16():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(is_empty=bool_0)
    str_0 = immutable_list_0.__str__()
    immutable_list_1 = immutable_list_0.unshift(str_0)
    bool_1 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_1.find(bool_0)


def test_case_17():
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(bool_0)
    var_0 = immutable_list_1.__add__(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_18():
    bytes_0 = b"\x14V\x94\xb2\x8e\tx\xdb\x7f\x1f\x15\xe1"
    immutable_list_0 = module_0.ImmutableList()
    none_type_0 = None
    immutable_list_1 = module_0.ImmutableList(is_empty=none_type_0)
    bytes_1 = b"p"
    immutable_list_2 = immutable_list_0.append(bytes_0)
    str_0 = immutable_list_2.__str__()
    immutable_list_3 = module_0.ImmutableList(bytes_1)
    bool_0 = immutable_list_3.__eq__(bytes_0)
    none_type_1 = None
    bool_1 = immutable_list_3.__eq__(none_type_1)
    immutable_list_4 = immutable_list_0.append(immutable_list_1)
    var_0 = immutable_list_3.to_list()
    immutable_list_3.reduce(bytes_0, bytes_0)


def test_case_19():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_1.find(immutable_list_0)


def test_case_20():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0, is_empty=bool_0)
    immutable_list_0.find(bool_0)


def test_case_21():
    bool_0 = True
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(bool_0, none_type_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.find(bool_0)


def test_case_22():
    bytes_0 = b"\x14V\x94\xb2\x8e\tx\xdb\x7f\x1f\x15\xe1"
    immutable_list_0 = module_0.ImmutableList()
    none_type_0 = None
    immutable_list_1 = module_0.ImmutableList(is_empty=none_type_0)
    bytes_1 = b"p"
    immutable_list_2 = immutable_list_0.append(bytes_0)
    immutable_list_3 = module_0.ImmutableList(bytes_1)
    bool_0 = immutable_list_3.__eq__(bytes_0)
    immutable_list_4 = immutable_list_0.append(immutable_list_1)
    var_0 = immutable_list_3.to_list()
    bool_1 = immutable_list_0.__eq__(immutable_list_4)
    immutable_list_3.find(var_0)
