# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis.builtins.da as module_0


def test_case_0():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()


def test_case_1():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()


def test_case_2():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()
    str_1 = denmark_spec_provider_0.cpr()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()
    str_2 = denmark_spec_provider_1.get_current_locale()


def test_case_3():
    str_0 = ""
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider(str_0)


def test_case_4():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_0.cpr()
    none_type_0 = None
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider(none_type_0)


def test_case_5():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider()
    str_0 = denmark_spec_provider_1.cpr()
    denmark_spec_provider_2 = module_0.DenmarkSpecProvider()
    str_1 = denmark_spec_provider_2.cpr()


def test_case_6():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    none_type_0 = None
    str_0 = denmark_spec_provider_0.cpr()
    denmark_spec_provider_1 = module_0.DenmarkSpecProvider(none_type_0)
    dict_0 = {}
    none_type_1 = denmark_spec_provider_1.update_dataset(dict_0)
