# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0
import dataclasses as module_1


def test_case_0():
    timer_error_0 = module_0.TimerError()


def test_case_1():
    none_type_0 = None
    timer_error_0 = module_0.TimerError()
    timer_error_1 = module_0.TimerError()
    timer_0 = module_0.Timer()
    var_0 = module_1.dataclass(frozen=timer_0)
    var_1 = var_0.__eq__(none_type_0)
    timer_1 = timer_0.__enter__()
    timer_0.start()


def test_case_2():
    none_type_0 = None
    str_0 = "1"
    timer_0 = module_0.Timer(none_type_0, str_0, str_0)
    none_type_1 = timer_0.start()


def test_case_3():
    float_arg_0 = module_0.FloatArg()
    timer_0 = module_0.Timer(initial_text=float_arg_0)
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    timer_1.__exit__()


def test_case_4():
    float_arg_0 = module_0.FloatArg()
    timer_0 = module_0.Timer(initial_text=float_arg_0)
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_1.__exit__()


def test_case_5():
    float_arg_0 = module_0.FloatArg()
    timer_0 = module_0.Timer()
    timer_1 = module_0.Timer(logger=float_arg_0)
    timer_2 = timer_1.__enter__()


def test_case_6():
    float_arg_0 = module_0.FloatArg()
    none_type_0 = None
    timer_0 = module_0.Timer(float_arg_0, float_arg_0, none_type_0, none_type_0)
    timer_1 = timer_0.__enter__()
    list_0 = [timer_0]
    none_type_1 = timer_1.__exit__(*list_0)
    timer_0.__exit__()


def test_case_7():
    float_arg_0 = module_0.FloatArg()
    float_arg_1 = module_0.FloatArg()
    timer_0 = module_0.Timer(float_arg_0, float_arg_0, float_arg_1)
    timer_1 = timer_0.__enter__()
    list_0 = []
    timer_1.__exit__(*list_0)


def test_case_8():
    float_arg_0 = module_0.FloatArg()
    timer_0 = module_0.Timer(float_arg_0, initial_text=float_arg_0)
    none_type_0 = None
    timer_1 = module_0.Timer(text=timer_0, initial_text=none_type_0)
    timer_error_0 = module_0.TimerError()
    timer_2 = timer_1.__enter__()
    none_type_1 = timer_0.__call__(timer_0)
    var_0 = timer_1.__repr__()
    list_0 = []
    none_type_2 = timer_2.__exit__(*list_0)
    timer_1.__exit__()
