# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    immutable_list_0.find(immutable_list_0)


def test_case_1():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    bool_0 = immutable_list_0.__eq__(dict_0)
    immutable_list_0.find(bool_0)


def test_case_2():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)


def test_case_3():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.__add__(bool_0)


def test_case_4():
    immutable_list_0 = module_0.ImmutableList()
    str_0 = immutable_list_0.find(immutable_list_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.filter(var_0)


def test_case_5():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    var_0 = immutable_list_0.__len__()
    immutable_list_0.find(var_0)


def test_case_6():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.to_list()


def test_case_7():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    immutable_list_1 = immutable_list_0.append(immutable_list_0)
    var_0 = immutable_list_1.__len__()
    str_0 = immutable_list_1.__str__()
    immutable_list_0.find(immutable_list_1)


def test_case_8():
    dict_0 = {}
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    str_0 = "GG!sFN;@4zz-eCfr&HS1"
    var_0 = immutable_list_0.reduce(str_0, immutable_list_0)
    bool_0 = immutable_list_0.__eq__(none_type_0)
    immutable_list_1 = immutable_list_0.append(str_0)
    list_0 = []
    var_1 = immutable_list_1.reduce(var_0, bool_0)
    var_2 = var_0.find(list_0)
    immutable_list_0.map(dict_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_10():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    var_0 = immutable_list_0.reduce(bool_0, immutable_list_0)
    str_0 = immutable_list_0.__str__()
    dict_0 = {}
    var_1 = var_0.reduce(var_0, immutable_list_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_2 = immutable_list_0.find(str_0)
    immutable_list_2 = module_0.ImmutableList(dict_0)
    immutable_list_1.filter(var_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_12():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    immutable_list_0.find(immutable_list_0)


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()
    str_0 = immutable_list_0.__str__()
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_14():
    immutable_list_0 = module_0.ImmutableList()
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    str_0 = immutable_list_0.__str__()
    str_1 = immutable_list_0.__str__()
    dict_0 = {}
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    var_0 = immutable_list_0.find(str_1)
    immutable_list_2 = module_0.ImmutableList(str_1)
    immutable_list_3 = module_0.ImmutableList(dict_0, is_empty=var_0)
    immutable_list_4 = immutable_list_2.append(immutable_list_1)
    immutable_list_5 = immutable_list_0.append(immutable_list_1)
    immutable_list_6 = module_0.ImmutableList()
    immutable_list_3.reduce(var_0, immutable_list_2)


def test_case_15():
    immutable_list_0 = module_0.ImmutableList()


def test_case_16():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    immutable_list_1 = immutable_list_0.append(immutable_list_0)
    immutable_list_1.find(dict_0)


def test_case_17():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_0.filter(immutable_list_0)


def test_case_18():
    float_0 = 1210.67657
    set_0 = {float_0, float_0, float_0}
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(tail=set_0, is_empty=bool_0)
    immutable_list_0.__add__(immutable_list_0)


def test_case_19():
    str_0 = "ED"
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    immutable_list_1 = module_0.ImmutableList()
    immutable_list_2 = immutable_list_1.append(str_0)
    immutable_list_3 = immutable_list_2.append(str_0)
    immutable_list_4 = immutable_list_3.unshift(str_0)
    immutable_list_4.reduce(str_0, str_0)


def test_case_20():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    bool_0 = immutable_list_0.__eq__(none_type_0)
    immutable_list_1 = immutable_list_0.unshift(none_type_0)
    bool_1 = immutable_list_1.__eq__(immutable_list_1)
    immutable_list_2 = immutable_list_1.unshift(immutable_list_1)
    immutable_list_1.map(immutable_list_1)


def test_case_21():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0)
    immutable_list_1 = immutable_list_0.append(immutable_list_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_0.find(immutable_list_1)


def test_case_22():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = module_0.ImmutableList(immutable_list_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_2)
    var_0 = immutable_list_2.to_list()
    immutable_list_2.find(var_0)


def test_case_23():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_2 = module_0.ImmutableList(immutable_list_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_1)
    immutable_list_2.find(bool_0)
