# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.transformers.yield_from as module_0
import typed_ast._ast3 as module_1
import typed_ast.ast3 as module_2


def test_case_0():
    float_0 = 1415.9154
    yield_from_transformer_0 = module_0.YieldFromTransformer(float_0)
    yield_from_transformer_0.visit(yield_from_transformer_0)


def test_case_1():
    str_0 = module_1.Str()
    yield_from_transformer_0 = module_0.YieldFromTransformer(str_0)


def test_case_2():
    str_0 = "~C@z"
    yield_from_transformer_0 = module_0.YieldFromTransformer(str_0)
    var_0 = module_2.parse(str_0)
    var_1 = yield_from_transformer_0.visit(var_0)


def test_case_3():
    float_0 = 1414.3368063177834
    yield_from_transformer_0 = module_0.YieldFromTransformer(float_0)
    list_0 = [yield_from_transformer_0, yield_from_transformer_0]
    module_0 = module_1.Module(*list_0)
    a_s_t_0 = yield_from_transformer_0.visit(module_0)
