# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import builtins as module_1
import inspect as module_2


def test_case_0():
    bool_0 = module_0.is_atty()
    bool_1 = module_0.is_atty()
    bool_2 = module_0.is_atty()
    var_0 = module_0.has_message_body(bool_2)


def test_case_1():
    int_0 = 1887
    module_0.remove_entity_headers(int_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    int_0 = 1887
    module_0.is_entity_header(int_0)


def test_case_4():
    default_0 = module_0.Default()
    set_0 = {default_0}
    module_0.is_hop_by_hop_header(set_0)


def test_case_5():
    dict_0 = {}
    default_0 = module_0.Default()
    var_0 = default_0.__repr__()
    str_0 = default_0.__str__()
    var_1 = module_0.remove_entity_headers(dict_0)
    var_2 = var_1.__repr__()
    int_0 = 67
    var_3 = module_0.has_message_body(int_0)
    module_1.object(*var_3)


def test_case_6():
    bool_0 = module_0.is_atty()
    int_0 = 307
    var_0 = module_0.has_message_body(int_0)
    tuple_0 = ()
    var_1 = module_2.ismodule(tuple_0)


def test_case_7():
    str_0 = "P\x0b\n"
    dict_0 = {str_0: str_0, str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0, dict_0)


def test_case_8():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    var_0 = default_0.__repr__()
    bool_0 = module_0.is_atty()
    dict_0 = {var_0: default_0}
    var_1 = module_0.remove_entity_headers(dict_0)
    str_1 = var_1.__str__()
    int_0 = 304
    var_2 = module_0.has_message_body(int_0)
    var_3 = module_2.ismodule(int_0)
    var_4 = module_0.has_message_body(var_2)
    module_0.remove_entity_headers(var_3, var_4)
