# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0


def test_case_0():
    none_type_0 = None
    none_type_1 = module_0.debug(none_type_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    str_0 = "mNB?)i]#sE`Y"
    set_0 = {str_0, str_0, str_0, str_0}
    callable_0 = module_0.eager(set_0)
    list_0 = []
    variables_generator_0 = module_0.VariablesGenerator(*list_0)


def test_case_3():
    str_0 = "RKqB\\.2Xz,K19\tAR"
    module_0.get_source(str_0)


def test_case_4():
    dict_0 = {}
    variables_generator_0 = module_0.VariablesGenerator(**dict_0)
    float_0 = -2355.6857
    none_type_0 = module_0.warn(float_0)


def test_case_5():
    float_0 = -3812.39005
    variables_generator_0 = module_0.VariablesGenerator()
    callable_0 = module_0.eager(float_0)
    none_type_0 = module_0.warn(float_0)
    none_type_1 = module_0.debug(callable_0)
    int_0 = -5542
    callable_0.__call__(none_type_1, none_type_0, int_0, module=callable_0)
