# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import inspect as module_1


def test_case_0():
    int_0 = 422
    var_0 = module_0.has_message_body(int_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    bytes_0 = b"Upgrade Required"
    bool_0 = False
    dict_0 = {bytes_0: bytes_0, bytes_0: bool_0, bytes_0: bool_0, bool_0: bytes_0}
    module_0.remove_entity_headers(dict_0)


def test_case_4():
    default_0 = module_0.Default()
    var_0 = default_0.__repr__()
    var_1 = default_0.__repr__()
    var_2 = module_0.is_hop_by_hop_header(var_1)


def test_case_5():
    default_0 = module_0.Default()
    module_0.remove_entity_headers(default_0, default_0)


def test_case_6():
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    bool_0 = module_0.is_atty()


def test_case_7():
    bool_0 = True
    var_0 = module_0.has_message_body(bool_0)
    module_0.is_hop_by_hop_header(bool_0)


def test_case_8():
    int_0 = 304
    var_0 = module_0.has_message_body(int_0)
    bool_0 = module_0.is_atty()
    default_0 = module_0.Default()
    var_1 = default_0.__repr__()
    bool_1 = True
    var_2 = default_0.__repr__()
    var_3 = default_0.__repr__()
    var_4 = module_1.ismodule(var_3)
    str_0 = var_4.__str__()
    var_5 = module_0.has_message_body(bool_1)
    module_0.remove_entity_headers(bool_1)
