# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.immutable_list as module_0


def test_case_0():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0, is_empty=dict_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_0)
    immutable_list_0.find(immutable_list_0)


def test_case_1():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0, is_empty=dict_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    bool_0 = immutable_list_0.__eq__(immutable_list_1)
    var_0 = immutable_list_0.to_list()
    immutable_list_0.find(immutable_list_0)


def test_case_2():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_3():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(none_type_0)
    immutable_list_1 = immutable_list_0.__add__(immutable_list_0)
    immutable_list_0.__add__(none_type_0)


def test_case_4():
    none_type_0 = None
    bool_0 = False
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0, is_empty=bool_0)
    var_0 = immutable_list_0.__len__()


def test_case_5():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = module_0.ImmutableList(immutable_list_0, immutable_list_0)
    var_0 = immutable_list_1.__len__()
    immutable_list_1.find(var_0)


def test_case_6():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    var_0 = immutable_list_0.to_list()


def test_case_7():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    str_0 = immutable_list_1.__str__()
    immutable_list_1.find(immutable_list_0)


def test_case_8():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = module_0.ImmutableList()
    immutable_list_1.map(immutable_list_0)


def test_case_9():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_0.filter(immutable_list_0)


def test_case_10():
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.filter(immutable_list_0)


def test_case_11():
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.find(immutable_list_0)
    immutable_list_1 = immutable_list_0.unshift(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_12():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList()
    var_0 = immutable_list_0.reduce(bool_0, bool_0)


def test_case_13():
    immutable_list_0 = module_0.ImmutableList()


def test_case_14():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0, is_empty=dict_0)
    str_0 = immutable_list_0.__str__()
    immutable_list_0.find(immutable_list_0)


def test_case_15():
    str_0 = "D$"
    immutable_list_0 = module_0.ImmutableList(is_empty=str_0)
    var_0 = immutable_list_0.append(immutable_list_0)
    immutable_list_0.filter(var_0)


def test_case_16():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList()
    immutable_list_1 = immutable_list_0.unshift(none_type_0)
    immutable_list_2 = immutable_list_1.append(none_type_0)
    immutable_list_2.filter(none_type_0)


def test_case_17():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0, is_empty=dict_0)
    str_0 = immutable_list_0.__len__()
    immutable_list_0.find(immutable_list_0)


def test_case_18():
    bool_0 = True
    immutable_list_0 = module_0.ImmutableList(bool_0, is_empty=bool_0)
    immutable_list_1 = immutable_list_0.append(bool_0)
    bool_1 = immutable_list_1.__eq__(immutable_list_0)
    immutable_list_1.find(immutable_list_0)


def test_case_19():
    float_0 = -3094.362
    list_0 = [float_0, float_0]
    immutable_list_0 = module_0.ImmutableList(list_0)
    none_type_0 = None
    bytes_0 = b"\x84N\xec\xdf\xad\xe1\xccof\xf2\xe7\x86"
    immutable_list_1 = immutable_list_0.unshift(bytes_0)
    immutable_list_1.map(none_type_0)


def test_case_20():
    dict_0 = {}
    immutable_list_0 = module_0.ImmutableList(dict_0, is_empty=dict_0)
    immutable_list_0.find(immutable_list_0)


def test_case_21():
    immutable_list_0 = module_0.ImmutableList()
    none_type_0 = None
    immutable_list_1 = module_0.ImmutableList()
    bool_0 = immutable_list_1.__eq__(none_type_0)
    var_0 = immutable_list_0.reduce(immutable_list_0, immutable_list_0)
    var_1 = immutable_list_0.find(var_0)
    immutable_list_2 = immutable_list_0.append(immutable_list_0)
    str_0 = var_0.__str__()
    bool_1 = immutable_list_0.__eq__(var_1)
    bool_2 = True
    immutable_list_3 = module_0.ImmutableList(bool_0, is_empty=bool_2)
    bool_3 = immutable_list_1.__eq__(bool_1)
    immutable_list_3.reduce(var_0, var_1)


def test_case_22():
    none_type_0 = None
    immutable_list_0 = module_0.ImmutableList(tail=none_type_0)
    var_0 = immutable_list_0.__len__()
    none_type_1 = None
    immutable_list_1 = module_0.ImmutableList()
    var_1 = immutable_list_1.find(none_type_1)
    none_type_2 = None
    bool_0 = True
    int_0 = 964
    dict_0 = {bool_0: bool_0, bool_0: int_0, int_0: bool_0}
    bool_1 = True
    immutable_list_2 = module_0.ImmutableList(bool_1, is_empty=bool_1)
    immutable_list_3 = immutable_list_2.append(dict_0)
    immutable_list_3.reduce(none_type_2, none_type_2)
