# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import builtins as module_1
import inspect as module_2


def test_case_0():
    bool_0 = True
    var_0 = module_0.has_message_body(bool_0)


def test_case_1():
    bool_0 = True
    module_0.remove_entity_headers(bool_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    default_0 = module_0.Default()


def test_case_4():
    bool_0 = True
    var_0 = module_0.has_message_body(bool_0)
    module_0.is_entity_header(var_0)


def test_case_5():
    bool_0 = module_0.is_atty()
    var_0 = module_0.has_message_body(bool_0)
    none_type_0 = None
    module_0.is_hop_by_hop_header(none_type_0)


def test_case_6():
    bool_0 = module_0.is_atty()
    bool_1 = True
    var_0 = module_0.has_message_body(bool_1)
    none_type_0 = None
    default_0 = module_0.Default()
    str_0 = default_0.__str__()
    dict_0 = {}
    var_1 = module_0.remove_entity_headers(dict_0)
    int_0 = 100
    var_2 = var_1.__repr__()
    var_3 = int_0.__repr__()
    module_0.Default(*none_type_0)


def test_case_7():
    object_0 = module_1.object()
    bool_0 = module_0.is_atty()
    int_0 = 120
    var_0 = module_0.has_message_body(int_0)


def test_case_8():
    bool_0 = module_0.is_atty()
    var_0 = bool_0.__repr__()
    dict_0 = {var_0: bool_0}
    var_1 = module_0.remove_entity_headers(dict_0)


def test_case_9():
    none_type_0 = None
    bool_0 = module_0.is_atty()
    var_0 = module_2.ismodule(none_type_0)
    var_1 = var_0.__repr__()
    str_0 = var_1.__str__()
    var_2 = module_0.is_hop_by_hop_header(var_1)
    var_3 = var_1.__repr__()
    var_4 = var_1.__repr__()
    var_5 = module_0.has_message_body(var_0)
    var_6 = module_0.is_hop_by_hop_header(var_4)
    str_1 = var_6.__str__()
    dict_0 = {str_0: var_1, var_4: var_6, var_4: var_0}
    var_7 = module_0.remove_entity_headers(dict_0)
    int_0 = 204
    var_8 = module_0.is_entity_header(var_1)
    var_9 = module_0.has_message_body(int_0)
    module_0.is_hop_by_hop_header(var_9)
