# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.yield_from as module_1


def test_case_0():
    load_0 = module_0.Load()
    yield_from_transformer_0 = module_1.YieldFromTransformer(load_0)
    a_s_t_0 = yield_from_transformer_0.visit(load_0)


def test_case_1():
    load_0 = module_0.Load()
    yield_from_transformer_0 = module_1.YieldFromTransformer(load_0)


def test_case_2():
    none_type_0 = None
    yield_from_transformer_0 = module_1.YieldFromTransformer(none_type_0)
    list_0 = [
        yield_from_transformer_0,
        none_type_0,
        yield_from_transformer_0,
        none_type_0,
    ]
    function_def_0 = module_0.FunctionDef(*list_0)
    a_s_t_0 = yield_from_transformer_0.visit(function_def_0)


def test_case_3():
    none_type_0 = None
    yield_from_transformer_0 = module_1.YieldFromTransformer(none_type_0)
    list_0 = [
        yield_from_transformer_0,
        none_type_0,
        yield_from_transformer_0,
        yield_from_transformer_0,
    ]
    list_1 = [list_0]
    interactive_0 = module_0.Interactive(*list_1)
    a_s_t_0 = yield_from_transformer_0.visit(interactive_0)
