# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1
import sanic.utils as module_2


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    bool_0 = False
    config_0 = module_0.Config(keep_alive=bool_0, converters=bool_0)
    none_type_0 = config_0.update(**config_0)


def test_case_2():
    bool_0 = True
    var_0 = module_1.isclass(bool_0)
    bool_1 = True
    config_0 = module_0.Config(var_0, var_0, bool_1)
    var_0.update()


def test_case_3():
    float_0 = 1.0
    module_0.Config(float_0)


def test_case_4():
    config_0 = module_0.Config()
    bool_0 = False
    config_1 = module_0.Config()
    config_1.__getattr__(bool_0)


def test_case_5():
    bool_0 = False
    config_0 = module_0.Config(keep_alive=bool_0, converters=bool_0)
    config_0.update_config(bool_0)


def test_case_6():
    str_0 = "DO+4XIEf/=Aw"
    config_0 = module_0.Config(env_prefix=str_0)
    list_0 = []
    none_type_0 = config_0.update(*list_0)
    config_1 = module_0.Config(converters=config_0)
    var_0 = module_1.getmembers(str_0)
    var_0.update_config(str_0)


def test_case_7():
    none_type_0 = None
    str_0 = "keepAalive"
    config_0 = module_0.Config(env_prefix=str_0, keep_alive=none_type_0)
    config_0.update_config(none_type_0)


def test_case_8():
    config_0 = module_0.Config()
    var_0 = module_1.isdatadescriptor(config_0)
    str_0 = "_converters"
    none_type_0 = config_0.__setitem__(str_0, var_0)
    config_0.register_type(var_0)


def test_case_9():
    config_0 = module_0.Config()
    config_1 = module_0.Config()
    config_0.__getattr__(config_0)


def test_case_10():
    str_0 = "DO+4XIEf/=Aw"
    config_0 = module_0.Config(env_prefix=str_0)
    config_0.update_config(str_0)


def test_case_11():
    config_0 = module_0.Config()
    bool_0 = False
    config_1 = module_0.Config()
    var_0 = config_0.update_config(config_1)
    var_1 = module_1.getmembers(var_0)
    str_0 = "^\rw]<N,9g9}JC'\nWQ"
    var_1.__setitem__(str_0, bool_0)


def test_case_12():
    config_0 = module_0.Config()
    var_0 = config_0.update_config(config_0)
    none_type_0 = config_0.register_type(var_0)
    config_0.register_type(var_0)


def test_case_13():
    config_0 = module_0.Config()
    var_0 = module_1.getmembers(config_0)
    list_0 = [var_0, config_0, config_0]
    none_type_0 = config_0.update(*list_0)
    str_0 = "5\x0cY\\n"
    module_2.load_module_from_file_location(str_0, config_0)
