# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    timer_0 = module_0.Timer()


def test_case_1():
    timer_0 = module_0.Timer()
    none_type_0 = timer_0.start()
    none_type_1 = timer_0.__exit__()


def test_case_2():
    none_type_0 = None
    str_0 = "?EeazGekMq>T=j"
    timer_0 = module_0.Timer(none_type_0, initial_text=str_0, logger=none_type_0)
    timer_0.__exit__()


def test_case_3():
    timer_0 = module_0.Timer()
    none_type_0 = timer_0.start()
    timer_0.__enter__()


def test_case_4():
    str_0 = "Ga\tv7g <E8z$azel"
    dict_0 = {str_0: str_0}
    timer_0 = module_0.Timer(dict_0, initial_text=dict_0)
    timer_1 = timer_0.__enter__()
    var_0 = timer_0.__eq__(str_0)
    var_0.__setitem__(timer_0, dict_0)


def test_case_5():
    none_type_0 = None
    bool_0 = True
    timer_0 = module_0.Timer(text=none_type_0, initial_text=bool_0, logger=bool_0)
    var_0 = timer_0.__repr__()
    timer_0.start()


def test_case_6():
    float_arg_0 = module_0.FloatArg()
    none_type_0 = None
    timer_0 = module_0.Timer(text=float_arg_0, logger=none_type_0)
    float_arg_1 = module_0.FloatArg()
    timer_1 = timer_0.__enter__()
    none_type_1 = timer_0.__exit__()
    var_0 = timer_1.__eq__(timer_1)
    timer_2 = module_0.Timer(initial_text=float_arg_1)
    var_0.__contains__(float_arg_1)


def test_case_7():
    str_0 = "Ga\tv7g <E8z$azel"
    dict_0 = {str_0: str_0}
    timer_0 = module_0.Timer(dict_0, initial_text=dict_0)
    timer_1 = timer_0.__enter__()
    var_0 = timer_0.__eq__(str_0)
    timer_0.stop()


def test_case_8():
    str_0 = "Ga\tv7g <E8z$azel"
    timer_0 = module_0.Timer(str_0, initial_text=str_0)
    timer_1 = timer_0.__enter__()
    var_0 = timer_0.__eq__(str_0)
    float_0 = timer_0.stop()
    none_type_0 = None
    timer_0.__contains__(none_type_0)


def test_case_9():
    bytes_0 = b"GY\xa4\xd3Z\x8aKN\xf9P"
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0]
    timer_0 = module_0.Timer(logger=list_0)
    str_0 = "Ga\tv7g <E8z$azel"
    dict_0 = {str_0: str_0}
    timer_1 = module_0.Timer(dict_0, timer_0, bytes_0)
    timer_2 = timer_1.__enter__()
    timer_2.__exit__()
