# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.base as module_1


def test_case_0():
    subscript_0 = module_0.Subscript()
    base_import_rewrite_0 = module_1.BaseImportRewrite(subscript_0)


def test_case_1():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0]
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0 = module_1.BaseImportRewrite(none_type_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_2():
    starred_0 = module_0.Starred()
    base_import_rewrite_0 = module_1.BaseImportRewrite(starred_0)
    list_0 = [base_import_rewrite_0]
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)
