# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pymonet.validation as module_0
import builtins as module_1


def test_case_0():
    float_0 = -843.89505
    validation_0 = module_0.Validation(float_0, float_0)
    var_0 = validation_0.to_lazy()
    var_1 = validation_0.__eq__(validation_0)
    validation_0.to_try()


def test_case_1():
    int_0 = -15
    none_type_0 = None
    validation_0 = module_0.Validation(int_0, none_type_0)
    var_0 = validation_0.__eq__(int_0)
    validation_0.is_success()


def test_case_2():
    tuple_0 = ()
    validation_0 = module_0.Validation(tuple_0, tuple_0)
    var_0 = validation_0.__str__()
    var_1 = validation_0.to_maybe()
    var_1.bind(validation_0)


def test_case_3():
    bytes_0 = b"\xffE\x01\xfa\xb0\xed:\xa0\x91\x123\xae"
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.__str__()
    var_1 = validation_0.to_lazy()
    var_2 = validation_0.is_fail()
    var_3 = validation_0.to_box()
    var_2.to_try()


def test_case_4():
    dict_0 = {}
    validation_0 = module_0.Validation(dict_0, dict_0)
    var_0 = validation_0.__eq__(validation_0)
    var_1 = validation_0.to_maybe()
    validation_1 = module_0.Validation(var_1, var_0)
    var_2 = validation_0.__eq__(var_0)
    var_3 = validation_0.to_either()
    var_2.bind(validation_1)


def test_case_5():
    bytes_0 = b"\n:\xcf\x16\xb8\xcd\xd1\x07\xbf\xe5\t\xb6\x88"
    validation_0 = module_0.Validation(bytes_0, bytes_0)
    var_0 = validation_0.to_either()
    var_1 = var_0.to_try()
    var_2 = var_0.to_maybe()
    var_3 = var_2.to_either()
    var_3.is_fail()


def test_case_6():
    int_0 = 265
    dict_0 = {}
    validation_0 = module_0.Validation(dict_0, dict_0)
    var_0 = validation_0.__eq__(int_0)
    bool_0 = False
    bool_1 = False
    bool_2 = True
    tuple_0 = (bool_0, bool_1, bool_2)
    var_1 = validation_0.to_maybe()
    var_2 = var_0.__eq__(tuple_0)
    var_0.to_box()


def test_case_7():
    bool_0 = False
    validation_0 = module_0.Validation(bool_0, bool_0)


def test_case_8():
    int_0 = -16
    none_type_0 = None
    validation_0 = module_0.Validation(int_0, none_type_0)
    var_0 = validation_0.to_box()
    validation_0.is_success()


def test_case_9():
    bool_0 = True
    none_type_0 = None
    validation_0 = module_0.Validation(none_type_0, none_type_0)
    validation_0.map(bool_0)


def test_case_10():
    int_0 = -16
    none_type_0 = None
    validation_0 = module_0.Validation(int_0, none_type_0)
    validation_0.bind(int_0)


def test_case_11():
    bool_0 = True
    bytes_0 = b"\xa8%\xf7\xf0\x83\xfd)\x04!\xff\xb4n\x82;"
    none_type_0 = None
    validation_0 = module_0.Validation(bytes_0, none_type_0)
    validation_0.ap(bool_0)


def test_case_12():
    int_0 = -16
    none_type_0 = None
    validation_0 = module_0.Validation(int_0, none_type_0)
    var_0 = validation_0.to_box()


def test_case_13():
    str_0 = "lI.WPu6F*)G'K02u"
    validation_0 = module_0.Validation(str_0, str_0)
    var_0 = validation_0.to_lazy()
    var_1 = var_0.to_maybe()
    var_2 = var_0.__str__()
    var_3 = var_1.to_lazy()
    var_4 = var_3.to_either()
    var_5 = var_3.to_try()
    var_5.is_success()


def test_case_14():
    int_0 = -1567
    validation_0 = module_0.Validation(int_0, int_0)
    validation_0.to_try()


def test_case_15():
    int_0 = 265
    dict_0 = {}
    validation_0 = module_0.Validation(dict_0, dict_0)
    var_0 = validation_0.__eq__(int_0)
    bool_0 = False
    var_1 = validation_0.to_maybe()
    var_2 = var_0.__eq__(validation_0)
    object_0 = module_1.object()
    validation_1 = module_0.Validation(var_2, var_0)
    validation_2 = module_0.Validation(object_0, bool_0)
    var_3 = validation_0.__eq__(validation_2)
    var_4 = validation_0.to_either()
    validation_2.bind(var_0)


def test_case_16():
    float_0 = 1362.5111
    dict_0 = {float_0: float_0}
    validation_0 = module_0.Validation(dict_0, dict_0)
    var_0 = validation_0.__eq__(validation_0)
    var_1 = validation_0.to_maybe()
    var_2 = validation_0.to_lazy()
    object_0 = module_1.object()
    validation_1 = module_0.Validation(object_0, object_0)
    var_3 = validation_0.__eq__(object_0)
    var_4 = var_2.to_either()
    var_5 = var_2.bind(var_1)
    var_6 = validation_0.to_maybe()
    var_7 = var_1.bind(var_2)
    var_8 = var_1.ap(dict_0)
    var_9 = var_6.bind(var_5)
    var_10 = var_5.map(var_1)
    var_10.to_box()
