# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.base as module_1
import typed_ast.ast3 as module_2


def test_case_0():
    expr_0 = module_0.expr()
    base_import_rewrite_0 = module_1.BaseImportRewrite(expr_0)


def test_case_1():
    expr_0 = module_0.expr()
    list_0 = [expr_0, expr_0]
    base_import_rewrite_0 = module_1.BaseImportRewrite(expr_0)
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_2():
    name_constant_0 = module_0.NameConstant()
    base_import_rewrite_0 = module_1.BaseImportRewrite(name_constant_0)
    var_0 = module_2.dump(name_constant_0)
    list_0 = [var_0, var_0]
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_3():
    name_constant_0 = module_0.NameConstant()
    var_0 = module_2.iter_child_nodes(name_constant_0)
    base_import_rewrite_0 = module_1.BaseImportRewrite(var_0)
    list_0 = [var_0, var_0]
    import_from_0 = module_0.ImportFrom(*list_0)
    var_1 = base_import_rewrite_0.visit_ImportFrom(import_from_0)


def test_case_4():
    none_type_0 = None
    base_import_rewrite_0 = module_1.BaseImportRewrite(none_type_0)
    list_0 = [none_type_0, none_type_0, none_type_0]
    import_from_0 = module_0.ImportFrom(*list_0)
    base_import_rewrite_0.visit_ImportFrom(import_from_0)
