# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.helpers as module_0
import inspect as module_1


def test_case_0():
    bool_0 = True
    var_0 = module_0.has_message_body(bool_0)


def test_case_1():
    bytes_0 = b"@>\x92\xffA\xe7\xdc\xc8\x94\xe8\xbdx\x05"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_2():
    bool_0 = module_0.is_atty()


def test_case_3():
    dict_0 = {}
    bool_0 = module_0.is_atty()
    module_0.is_hop_by_hop_header(dict_0)


def test_case_4():
    dict_0 = {}
    default_0 = module_0.Default(**dict_0)
    var_0 = default_0.__repr__()
    str_0 = default_0.__str__()


def test_case_5():
    int_0 = 3319
    var_0 = module_0.has_message_body(int_0)


def test_case_6():
    int_0 = 204
    var_0 = module_0.has_message_body(int_0)
    var_1 = var_0.__repr__()
    str_0 = ""
    var_2 = module_0.is_entity_header(str_0)
    var_3 = module_0.has_message_body(var_2)
    var_4 = module_1.ismodule(var_2)
    module_0.remove_entity_headers(var_4)


def test_case_7():
    str_0 = "Last-Modified"
    dict_0 = {str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0)


def test_case_8():
    bool_0 = module_0.is_atty()
    str_0 = "Last-Modified"
    dict_0 = {str_0: str_0}
    var_0 = module_0.remove_entity_headers(dict_0, dict_0)
    var_1 = module_0.remove_entity_headers(dict_0)
