# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import typed_ast._ast3 as module_0
import py_backwards.transformers.base as module_1


def test_case_0():
    and_0 = module_0.And()
    base_node_transformer_0 = module_1.BaseNodeTransformer(and_0)
