# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0


def test_case_0():
    str_0 = '"lk6*zv'
    none_type_0 = module_0.debug(str_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    tuple_0 = ()
    callable_0 = module_0.eager(tuple_0)
    none_type_0 = module_0.debug(callable_0)


def test_case_3():
    bytes_0 = b"\x92\xa6\xe8~\x92\x96~Uf]\xe5\xd5\x1am\x17\x89}"
    module_0.get_source(bytes_0)


def test_case_4():
    str_0 = "LEGSDF@ns;2Ksv']<_"
    none_type_0 = module_0.warn(str_0)


def test_case_5():
    bool_0 = False
    none_type_0 = module_0.warn(bool_0)
    list_0 = [none_type_0]
    none_type_1 = module_0.debug(list_0)
    str_0 = ""
    none_type_2 = module_0.warn(str_0)
    none_type_3 = module_0.warn(none_type_0)
    var_0 = module_0.eager(none_type_2)
    var_0.__call__(
        none_type_0, list_0, module=none_type_3, qualname=none_type_3, start=bool_0
    )
