# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sanic.config as module_0
import inspect as module_1


def test_case_0():
    config_0 = module_0.Config()


def test_case_1():
    str_0 = "df)($)O{+r\\f^T\ry=\r}"
    config_0 = module_0.Config(env_prefix=str_0)


def test_case_2():
    none_type_0 = None
    set_0 = set()
    config_0 = module_0.Config(none_type_0)
    config_0.__getattr__(set_0)


def test_case_3():
    config_0 = module_0.Config()
    none_type_0 = config_0.update(**config_0)


def test_case_4():
    config_0 = module_0.Config()
    bool_0 = True
    config_0.update_config(bool_0)


def test_case_5():
    config_0 = module_0.Config()
    none_type_0 = config_0.update_config(config_0)


def test_case_6():
    config_0 = module_0.Config()
    bytes_0 = b""
    none_type_0 = config_0.register_type(bytes_0)
    none_type_1 = config_0.update(**config_0)


def test_case_7():
    none_type_0 = None
    config_0 = module_0.Config(none_type_0, keep_alive=none_type_0)
    config_1 = module_0.Config(none_type_0, none_type_0, converters=none_type_0)
    none_type_1 = config_1.update(**config_0)
    config_2 = module_0.Config()
    none_type_2 = config_2.update()
    none_type_3 = config_2.register_type(config_2)


def test_case_8():
    config_0 = module_0.Config()
    config_0.log_response()


def test_case_9():
    bool_0 = False
    none_type_0 = None
    config_0 = module_0.Config(bool_0, converters=none_type_0)
    config_0.__setitem__(config_0, config_0)


def test_case_10():
    bool_0 = True
    config_0 = module_0.Config(keep_alive=bool_0)
    none_type_0 = None
    module_0.Config(bool_0, converters=none_type_0)


def test_case_11():
    float_0 = 2891.816251
    module_0.Config(converters=float_0)


def test_case_12():
    none_type_0 = None
    bool_0 = True
    config_0 = module_0.Config(none_type_0)
    none_type_1 = config_0.update(**config_0)
    config_1 = module_0.Config(converters=config_0)
    none_type_2 = config_0.register_type(bool_0)
    config_0.update_config(bool_0)


def test_case_13():
    str_0 = "+0JX6\r!cC3A%Dk"
    config_0 = module_0.Config()
    none_type_0 = config_0.update()
    config_1 = module_0.Config()
    none_type_1 = module_1.getmembers(config_0)
    config_0.update_config(str_0)


def test_case_14():
    none_type_0 = None
    bool_0 = True
    config_0 = module_0.Config(none_type_0)
    none_type_1 = config_0.update(**config_0)
    none_type_2 = config_0.register_type(bool_0)
    config_1 = module_0.Config(converters=config_0)
    config_0.register_type(bool_0)
