# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0


def test_case_0():
    int_0 = 246
    none_type_0 = module_0.debug(int_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    str_0 = '~s#e\nx\n?V"-\t- <'
    none_type_0 = module_0.warn(str_0)
    dict_0 = {}
    variables_generator_0 = module_0.VariablesGenerator(**dict_0)
    callable_0 = module_0.eager(none_type_0)
    variables_generator_0.__bool__()


def test_case_3():
    bytes_0 = b"\x9e\xb8\x8bF\xea\x16\xee\xd7\x85S~N22x\x84g$"
    module_0.get_source(bytes_0)


def test_case_4():
    str_0 = "\x0c[?cHQORSl5lv9]\n/@|"
    none_type_0 = module_0.warn(str_0)


def test_case_5():
    str_0 = ""
    callable_0 = module_0.eager(str_0)
    callable_0.__call__(str_0, str_0, start=str_0)
