# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import codetiming._timer as module_0


def test_case_0():
    float_arg_0 = module_0.FloatArg()


def test_case_1():
    timer_0 = module_0.Timer()
    none_type_0 = timer_0.start()
    float_0 = timer_0.stop()


def test_case_2():
    none_type_0 = None
    timer_0 = module_0.Timer(none_type_0, none_type_0)
    none_type_1 = timer_0.__repr__()
    timer_0.stop()


def test_case_3():
    bool_0 = True
    timer_0 = module_0.Timer(initial_text=bool_0)
    timer_1 = timer_0.__enter__()


def test_case_4():
    bool_0 = True
    timer_0 = module_0.Timer(initial_text=bool_0)
    timer_1 = timer_0.__enter__()
    none_type_0 = timer_0.__exit__()
    var_0 = timer_0.__eq__(timer_0)
    var_1 = timer_0.__repr__()
    var_2 = timer_0.__eq__(bool_0)
    module_0.FloatArg(**var_0)


def test_case_5():
    none_type_0 = None
    timer_0 = module_0.Timer(initial_text=none_type_0, logger=none_type_0)
    timer_1 = timer_0.__enter__()
    none_type_1 = timer_0.__exit__()
    timer_0.stop()


def test_case_6():
    bool_0 = True
    none_type_0 = None
    timer_0 = module_0.Timer(bool_0, initial_text=none_type_0)
    timer_1 = timer_0.__enter__()
    none_type_1 = timer_0.__exit__()
    timer_0.stop()


def test_case_7():
    bool_0 = True
    timer_0 = module_0.Timer(initial_text=bool_0)
    timer_1 = timer_0.__enter__()
    var_0 = timer_0.__eq__(timer_0)
    var_1 = timer_0.__repr__()
    var_2 = timer_0.__eq__(bool_0)
    timer_0.__enter__()


def test_case_8():
    str_0 = "</ArB.>\rwq=TYCy"
    timer_0 = module_0.Timer(initial_text=str_0)
    none_type_0 = timer_0.start()
    none_type_1 = None
    module_0.TimerError(**none_type_1)


def test_case_9():
    bool_0 = True
    timer_0 = module_0.Timer(bool_0, initial_text=bool_0, logger=bool_0)
    timer_0.__enter__()
